#Kotlin Speed & Incremental
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:InitiatingHeapOccupancyPercent=45
kotlin.incremental=true
kotlin.incremental.multiplatform=true
kotlin.incremental.js=true
kotlin.incremental.wasm=true
kotlin.mpp.enableCInteropCommonization=true

#Gradle Ultra Performance
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4096M -XX:+UseG1GC -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.workers.max=8

#Android & KMP
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.native.ignoreDisabledTargets=true

#TourOS Config
SUPABASE_URL=https://api.axileto.com
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzg2OTYyODU2LCJleHAiOjIxMDIzMjI4NTZ9.HzmIV6ONPXLRXSVkT1NdcLpKxf6DP_DqImuX0o8-8Lc