package com.mgacreative.touros.ui.localization

import com.mgacreative.touros.domain.model.AppLanguageItem
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Global Canlı Dil Yöneticisi — TourOS
 *
 * Tüm platformlarda (Web, Desktop, Android, iOS) seçili uygulama dilini reaktif tutar
 * ve menü, ekran başlığı, tablo etiketleri ve buton metinlerini 6 dilde dinamik olarak çözer.
 */
object AppLanguageManager {
    val supportedLanguages = listOf(
        AppLanguageItem("tr", "Türkçe", false, "🇹🇷"),
        AppLanguageItem("en", "English", false, "🇬🇧"),
        AppLanguageItem("de", "Deutsch", false, "🇩🇪"),
        AppLanguageItem("ru", "Русский", false, "🇷🇺"),
        AppLanguageItem("ar", "العربية", true, "🇸🇦"),
        AppLanguageItem("es", "Español", false, "🇪🇸")
    )

    private val _currentLanguage = MutableStateFlow(supportedLanguages.first())
    val currentLanguage: StateFlow<AppLanguageItem> = _currentLanguage.asStateFlow()

    private val dictionary: Map<String, Map<String, String>> = mapOf(
        "tr" to mapOf(
            // Navigation
            "Dashboard" to "Dashboard",
            "Turlar" to "Turlar",
            "Rezervasyon" to "Rezervasyon",
            "Oteller" to "Oteller",
            "Tur Operatörleri" to "Tur Operatörleri",
            "Ürünler" to "Ürünler",
            "Acente Web Sayfası" to "Acente Web Sayfası",
            "Fiyat & Kampanya" to "Fiyat & Kampanya",
            "Finans" to "Finans",
            "Fatura Yönetimi" to "Fatura Yönetimi",
            "Cari Hesaplar" to "Cari Hesaplar",
            "Gider Girişi" to "Gider Girişi",
            "Müşteriler & CRM" to "Müşteriler & CRM",
            "Analitik & Trend" to "Analitik & Trend",
            "Raporlar" to "Raporlar",
            "Ayarlar & Dil" to "Ayarlar & Dil",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "Şirket & Web Sayfası Ayarları",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin",
            "Ayar Kategorileri" to "Ayar Kategorileri",
            "Genel" to "Genel",
            "Marka" to "Marka",
            "Banka & PayPal" to "Banka & PayPal",
            "Vergi / Sezon" to "Vergi / Sezon",
            "Dil / Para Birimi" to "Dil / Para Birimi",
            "Dil ve Para Birimi Tercihleri" to "Dil ve Para Birimi Tercihleri",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller.",
            "Desteklenen Para Birimleri" to "Desteklenen Para Birimleri",
            "Desteklenen Panel Dilleri" to "Desteklenen Panel Dilleri",
            "Değişiklikleri Kaydet ✓" to "Değişiklikleri Kaydet ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "Tur Kataloğu",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "Aktif turlarınızı, paketleri ve rotaları yönetin",
            "+ Yeni Tur Ekle" to "+ Yeni Tur Ekle",
            "Tur adı, tur kodu veya şehir ile ara..." to "Tur adı, tur kodu veya şehir ile ara...",
            "Tüm Kategoriler" to "Tüm Kategoriler",
            "Günübirlik Tur" to "Günübirlik Tur",
            "Kültür Turu" to "Kültür Turu",
            "Macera & Doğa" to "Macera & Doğa",
            "Gemi & Cruise" to "Gemi & Cruise",
            "VIP Özel Tur" to "VIP Özel Tur",
            "Transfer Hizmeti" to "Transfer Hizmeti",
            "Tümü" to "Tümü",
            "Aktif" to "Aktif",
            "Pasif" to "Pasif",
            "Düzenle" to "Düzenle",
            "TUR KODU & ADI" to "TUR KODU & ADI",
            "KATEGORİ" to "KATEGORİ",
            "LOKASYON & SÜRE" to "LOKASYON & SÜRE",
            "DURUM" to "DURUM",
            "İŞLEM" to "İŞLEM",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "Tur ve Otel Arama Motoru",
            "Kalkış Şehri (Nereden)" to "Kalkış Şehri (Nereden)",
            "Nereye (Ülke / Bölge / Otel)" to "Nereye (Ülke / Bölge / Otel)",
            "Tur Operatörü Filtresi" to "Tur Operatörü Filtresi",
            "Maks. Bütçe (₺)" to "Maks. Bütçe (₺)",
            "TURLARI ARA 🔍" to "TURLARI ARA 🔍",
            "Hızlı Operatör Filtresi:" to "Hızlı Operatör Filtresi:",
            "Tüm Operatörler" to "Tüm Operatörler",
            "Tümünü Göster ➔" to "Tümünü Göster ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "Acente tarafından özel oluşturulan manuel tur paketleri.",
            "Tüm Tur Paketleri" to "Tüm Tur Paketleri",
            "Seçili Oteller" to "Seçili Oteller",
            "İncele" to "İncele",
            "Detaylar" to "Detaylar",
            "Paket Turlar" to "Paket Turlar",
            "Gezginler Tarafından Onaylanmış Her Şey Dahil Paket Turlar" to "Gezginler Tarafından Onaylanmış Her Şey Dahil Paket Turlar",
            "Oteller" to "Oteller",
            "Ayrıcalıklı konaklama ve seçkin 5 yıldızlı oteller" to "Ayrıcalıklı konaklama ve seçkin 5 yıldızlı oteller",
            "Son Dakika" to "Son Dakika",
            "Acele edin ve %70'e varan muhteşem indirimlerden yararlanın!" to "Acele edin ve %70'e varan muhteşem indirimlerden yararlanın!",
            "Charter & Tarifeli Uçuşlar" to "Charter & Tarifeli Uçuşlar",
            "En uygun fiyatlı direkt charter uçuşlar ve özel havayolu biletleri" to "En uygun fiyatlı direkt charter uçuşlar ve özel havayolu biletleri",
            "Bulunan Arama Fırsatları" to "Bulunan Arama Fırsatları",
            "Kriterlerinize uyan en uygun fiyatlı canlı tur ve otel teklifleri" to "Kriterlerinize uyan en uygun fiyatlı canlı tur ve otel teklifleri",
            "İNDİRİM" to "İNDİRİM",
            "Charter Uçuş Seferi" to "Charter Uçuş Seferi",
            "Direkt Uçuş" to "Direkt Uçuş",
            "Operatör Teklifi" to "Operatör Teklifi",
            "Gece" to "Gece",
            "En Düşük Fiyat" to "En Düşük Fiyat",
            "En Yüksek Fiyat" to "En Yüksek Fiyat",
            "Uçuş Seç" to "Uçuş Seç",
            "Tur Paketi" to "Tur Paketi",
            "Uçuşlar" to "Uçuşlar",
            "Destinasyon" to "Destinasyon",
            "Nereye (Destinasyon / Ülke)" to "Nereye (Destinasyon / Ülke)",
            "Tek Yön" to "Tek Yön",
            "Gidiş & Dönüş" to "Gidiş & Dönüş",
            "Gidiş Tarihi" to "Gidiş Tarihi",
            "Dönüş Tarihi" to "Dönüş Tarihi",
            "Dönüş Ekleyin" to "Dönüş Ekleyin",
            "Tarih" to "Tarih",
            "Gidiş Başlangıç" to "Gidiş Başlangıç",
            "Gidiş Bitiş" to "Gidiş Bitiş",
            "Opsiyon" to "Opsiyon",
            "Gece Sayısı" to "Gece Sayısı",
            "Turist Sayısı" to "Turist Sayısı",
            "Tur Operatörü" to "Tur Operatörü",
            "Tüm Operatörler" to "Tüm Operatörler",
            "Ülke" to "Ülke",
            "Türkiye" to "Türkiye",
            "Tüm Ülkeler" to "Tüm Ülkeler",
            "ARAMA BAŞLAT" to "ARAMA BAŞLAT",
            "3 Gece" to "3 Gece",
            "5 Gece" to "5 Gece",
            "7 Gece" to "7 Gece",
            "10 Gece" to "10 Gece",
            "14 Gece" to "14 Gece",
            "1 Yetişkin" to "1 Yetişkin",
            "2 Yetişkin" to "2 Yetişkin",
            "3 Yetişkin" to "3 Yetişkin",
            "2 Yetişkin + 1 Çocuk" to "2 Yetişkin + 1 Çocuk",
            "2 Yetişkin + 2 Çocuk" to "2 Yetişkin + 2 Çocuk",
            
            // Operational Screens
            "Operasyon Dashboard" to "Operasyon Dashboard",
            "Rol" to "Rol",
            "Canlı İşletme & Operasyon Özeti" to "Canlı İşletme & Operasyon Özeti",
            "Çıkış Yap" to "Çıkış Yap",
            "Rezervasyon Yönetimi" to "Rezervasyon Yönetimi",
            "Tüm turların rezervasyon taleplerini ve durumlarını takip edin" to "Tüm turların rezervasyon taleplerini ve durumlarını takip edin",
            "+ Yeni Rezervasyon" to "+ Yeni Rezervasyon",
            "Otel Portföy Yönetimi" to "Otel Portföy Yönetimi",
            "Konaklama tesislerini, kontrat şartlarını ve otel bilgilerini yönetin" to "Konaklama tesislerini, kontrat şartlarını ve otel bilgilerini yönetin",
            "+ Yeni Otel Ekle" to "+ Yeni Otel Ekle",
            "Finansal Raporlar & Analizler" to "Finansal Raporlar & Analizler",
            "KDV, Gelir-Gider, Likidite ve Kârlılık Dökümleri" to "KDV, Gelir-Gider, Likidite ve Kârlılık Dökümleri",
            "Cari Hesaplar & Mutabakat" to "Cari Hesaplar & Mutabakat",
            "Müşteri, acente ve tedarikçi bakiye dökümleri ve ekstreler" to "Müşteri, acente ve tedarikçi bakiye dökümleri ve ekstreler",
            "Tedarikçi Cari & Gider Girişi" to "Tedarikçi Cari & Gider Girişi",
            "Otel, araç yakıt ve rehber gider akışları ve cari takibi" to "Otel, araç yakıt ve rehber gider akışları ve cari takibi",
            "Müşteri Segmentleri & CRM" to "Müşteri Segmentleri & CRM",
            "Kullanıcı davranışlarına göre canlı segmentasyon ve müşteri dökümü" to "Kullanıcı davranışlarına göre canlı segmentasyon ve müşteri dökümü",
            "Analitik & Tahmin Grafikleri" to "Analitik & Tahmin Grafikleri",
            "Gerçekleşen satış trendleri ve AI gelecek tahmin analizi" to "Gerçekleşen satış trendleri ve AI gelecek tahmin analizi",
            "📊 Raporlar & Analitik Merkezi" to "📊 Raporlar & Analitik Merkezi",
            "Filtreli operasyon, otel, tur operatörü satış ve finansal çıktılar" to "Filtreli operasyon, otel, tur operatörü satış ve finansal çıktılar",

            // Company Settings Extra Keys
            "Acente Web Sitesi" to "Acente Web Sitesi",
            "Genel Firma Bilgileri" to "Genel Firma Bilgileri",
            "Fatura ve resmi yazışmalarda görünecek kurum ve iletişim bilgileri." to "Fatura ve resmi yazışmalarda görünecek kurum ve iletişim bilgileri.",
            "Firma Marka Adı" to "Firma Marka Adı",
            "Resmi Ticari Unvan" to "Resmi Ticari Unvan",
            "Vergi Dairesi" to "Vergi Dairesi",
            "Vergi Numarası" to "Vergi Numarası",
            "Ticaret Sicil No" to "Ticaret Sicil No",
            "MERSİS No" to "MERSİS No",
            "Kurumsal E-Posta" to "Kurumsal E-Posta",
            "Telefon Numarası" to "Telefon Numarası",
            "Firma Merkez Adresi" to "Firma Merkez Adresi",
            "Marka ve Kurumsal Renkler" to "Marka ve Kurumsal Renkler",
            "Acente kimliğinizi yansıtan logo ve kurumsal renk teması." to "Acente kimliğinizi yansıtan logo ve kurumsal renk teması.",
            "Kurumsal Logo" to "Kurumsal Logo",
            "📁 Dosyadan Görsel Seçin" to "📁 Dosyadan Görsel Seçin",
            "PNG, JPG veya SVG (Maksimum 1MB)" to "PNG, JPG veya SVG (Maksimum 1MB)",
            "Seçilen Dosya:" to "Seçilen Dosya:",
            "Ana Kurumsal Rengi" to "Ana Kurumsal Rengi",
            "Hex Renk Kodu (örn. #1F4E5F)" to "Hex Renk Kodu (örn. #1F4E5F)",
            "Acente Web Sayfası Ayarları (Sletat.ru Mimarisi)" to "Acente Web Sayfası Ayarları (Sletat.ru Mimarisi)",
            "Acente web sitenizin logosunu, header resmini, başlığını, sloganını ve iletişim detaylarını buradan güncelleyin." to "Acente web sitenizin logosunu, header resmini, başlığını, sloganını ve iletişim detaylarını buradan güncelleyin.",
            "1. Özel Logo Görseli (Sol Üst Header Logosu)" to "1. Özel Logo Görseli (Sol Üst Header Logosu)",
            "Logo Dosya Yolu veya Resim URL (Max 1MB)" to "Logo Dosya Yolu veya Resim URL (Max 1MB)",
            "📁 Dosyadan Seç" to "📁 Dosyadan Seç",
            "📌 Özel logo PNG/SVG formatında maksimum 1 MB olmalıdır." to "📌 Özel logo PNG/SVG formatında maksimum 1 MB olmalıdır.",
            "2. Header Banner Görseli (Web Sitesi Üst Arka Plan Resmi)" to "2. Header Banner Görseli (Web Sitesi Üst Arka Plan Resmi)",
            "Header Banner Dosya Yolu veya Resim URL (Max 1MB)" to "Header Banner Dosya Yolu veya Resim URL (Max 1MB)",
            "📌 Header banner çözünürlüğü 1600x400 px, maksimum 1 MB olmalıdır." to "📌 Header banner çözünürlüğü 1600x400 px, maksimum 1 MB olmalıdır.",
            "Aktif Banner Yolu:" to "Aktif Banner Yolu:",
            "3. Acente Web İletişim & WhatsApp Bilgileri (Web Sayfasına Özel)" to "3. Acente Web İletişim & WhatsApp Bilgileri (Web Sayfasına Özel)",
            "Resmi şirket fatura bilgilerinden bağımsız olarak web sitenizde ve müşteri taleplerinde kullanılacak iletişim bilgileri." to "Resmi şirket fatura bilgilerinden bağımsız olarak web sitenizde ve müşteri taleplerinde kullanılacak iletişim bilgileri.",
            "Web İletişim E-Postası (Rezervasyon Talepleri Buraya Düşer) *" to "Web İletişim E-Postası (Rezervasyon Talepleri Buraya Düşer) *",
            "Web İletişim Telefon Numarası *" to "Web İletişim Telefon Numarası *",
            "WhatsApp Hattı Telefon Numarası *" to "WhatsApp Hattı Telefon Numarası *",
            "Örn: 905300000000" to "Örn: 905300000000",
            "Web İletişim Merkez Adresi *" to "Web İletişim Merkez Adresi *",
            "4. Web Sitesi Başlık, Slogan ve Telif Metni" to "4. Web Sitesi Başlık, Slogan ve Telif Metni",
            "Web Site Başlığı / Acente Adı" to "Web Site Başlığı / Acente Adı",
            "Web Site Alt Başlığı (Slogan)" to "Web Site Alt Başlığı (Slogan)",
            "Footer / Telif Hakkı Metni" to "Footer / Telif Hakkı Metni",
            "🌐 OTA & Canlı Ürün Yayınlama Entegrasyonu" to "🌐 OTA & Canlı Ürün Yayınlama Entegrasyonu",
            "OTA Hub ve Pazaryeri kataloğundan 'Yayınla' (is_published=true) olarak işaretlenen tüm turlar, kar marjı hesaplanarak acente web sitenizde canlı olarak görünür." to "OTA Hub ve Pazaryeri kataloğundan 'Yayınla' (is_published=true) olarak işaretlenen tüm turlar, kar marjı hesaplanarak acente web sitenizde canlı olarak görünür.",
            "Vergi Oranları ve Operasyonel Sezonlar" to "Vergi Oranları ve Operasyonel Sezonlar",
            "Otomatik fiyatlama, KDV hesaplama ve sezonsal çalışma kuralları." to "Otomatik fiyatlama, KDV hesaplama ve sezonsal çalışma kuralları.",
            "Varsayılan KDV Oranı (%)" to "Varsayılan KDV Oranı (%)",
            "Tanımlı Operasyonel Sezonlar" to "Tanımlı Operasyonel Sezonlar",
            "Henüz tanımlanmış bir sezon bulunmamaktadır." to "Henüz tanımlanmış bir sezon bulunmamaktadır.",
            "Sil" to "Sil",
            "Yeni Sezon Ekle" to "Yeni Sezon Ekle",
            "Sezon Adı (örn. Yaz 2026)" to "Sezon Adı (örn. Yaz 2026)",
            "Başlangıç Tarihi" to "Başlangıç Tarihi",
            "Bitiş Tarihi" to "Bitiş Tarihi",
            "➕ Ekle" to "➕ Ekle",
            "💳 Banka & PayPal Ödeme Ayarları" to "💳 Banka & PayPal Ödeme Ayarları",
            "Müşterilerinizin havale/EFT ve PayPal ile ödeme yapabilmesi için banka ve PayPal hesap bilgilerinizi girin." to "Müşterilerinizin havale/EFT ve PayPal ile ödeme yapabilmesi için banka ve PayPal hesap bilgilerinizi girin.",
            "🏦 Banka Hesap Bilgileri (Havale / EFT)" to "🏦 Banka Hesap Bilgileri (Havale / EFT)",
            "Banka Adı & Şube" to "Banka Adı & Şube",
            "Örn: Türkiye İş Bankası - Kadıköy Şubesi" to "Örn: Türkiye İş Bankası - Kadıköy Şubesi",
            "Hesap Sahibi (Alıcı Adı)" to "Hesap Sahibi (Alıcı Adı)",
            "Örn: TourOS Turizm Seyahat A.Ş." to "Örn: TourOS Turizm Seyahat A.Ş.",
            "IBAN Numarası" to "IBAN Numarası",
            "Örn: TR92 0006 4000 0011 2233 4455 66" to "Örn: TR92 0006 4000 0011 2233 4455 66",
            "🅿️ PayPal Ödeme Ayarları" to "🅿️ PayPal Ödeme Ayarları",
            "PayPal Kurumsal E-Posta Adresi" to "PayPal Kurumsal E-Posta Adresi",
            "Örn: payment@acente.com" to "Örn: payment@acente.com",
            "PayPal.Me Ödeme Bağlantısı (URL)" to "PayPal.Me Ödeme Bağlantısı (URL)",
            "Örn: https://paypal.me/acenteisminiz" to "Örn: https://paypal.me/acenteisminiz",

            // Reports Screen Keys
            "⚡ Gelişmiş Rapor Filtreleme Header'ı" to "⚡ Gelişmiş Rapor Filtreleme Header'ı",
            "İstediğiniz tarih, ürün, tur operatörü veya duruma göre anlık rapor oluşturun" to "İstediğiniz tarih, ürün, tur operatörü veya duruma göre anlık rapor oluşturun",
            "Yazdır" to "Yazdır",
            "Rapor Türü Seçimi:" to "Rapor Türü Seçimi:",
            "Tüm Rezervasyonlar" to "Tüm Rezervasyonlar",
            "Tur & Operasyon" to "Tur & Operasyon",
            "Otel & Konaklama" to "Otel & Konaklama",
            "Tur Operatörü Satışları" to "Tur Operatörü Satışları",
            "Finans & Satış" to "Finans & Satış",
            "Müşteri & CRM" to "Müşteri & CRM",
            "Tarih Aralığı Filtresi:" to "Tarih Aralığı Filtresi:",
            "Bugün" to "Bugün",
            "Bu Hafta" to "Bu Hafta",
            "Bu Ay" to "Bu Ay",
            "Bu Yıl" to "Bu Yıl",
            "Tüm Zamanlar" to "Tüm Zamanlar",
            "Özel Tarih Aralığı" to "Özel Tarih Aralığı",
            "Başlangıç Tarihi" to "Başlangıç Tarihi",
            "Bitiş Tarihi" to "Bitiş Tarihi",
            "Tur Operatörü" to "Tur Operatörü",
            "Rezervasyon Durumu" to "Rezervasyon Durumu",
            "Anlık Arama" to "Anlık Arama",
            "Müşteri, kod, ürün..." to "Müşteri, kod, ürün...",
            "Toplam Rezervasyon" to "Toplam Rezervasyon",
            "Adet" to "Adet",
            "Hacim / Gece / Pax" to "Hacim / Gece / Pax",
            "Birim" to "Birim",
            "Toplam Ciro" to "Toplam Ciro",
            "Ort. Rezervasyon Tutarı" to "Ort. Rezervasyon Tutarı",
            "Filtrelenmiş Rapor Veri Listesi" to "Filtrelenmiş Rapor Veri Listesi",
            "Kayıt" to "Kayıt",
            "Seçilen filtrelere uygun rapor kaydı bulunamadı." to "Seçilen filtrelere uygun rapor kaydı bulunamadı.",
            "Kod" to "Kod",
            "Tür / Operatör" to "Tür / Operatör",
            "Müşteri" to "Müşteri",
            "Tarih / Gece" to "Tarih / Gece",
            "Tutar" to "Tutar",
            "Durum" to "Durum",
            "Otel" to "Otel",
            "Tur" to "Tur",
            "Kendi Ürünümüz" to "Kendi Ürünümüz",
            "Kendi Ürünlerimiz" to "Kendi Ürünlerimiz",
            "Gece" to "Gece",
            "Kişi" to "Kişi",
            "Bekliyor" to "Bekliyor",
            "Onaylandı" to "Onaylandı",
            "Tamamlandı" to "Tamamlandı",
            "İptal" to "İptal",

            // Invoice Management Keys
            "Fatura Yönetimi & e-Fatura" to "Fatura Yönetimi & e-Fatura",
            "Gelir / Gider e-faturaları oluşturun, onaylayın, PDF dışa aktarın ve iptal edin" to "Gelir / Gider e-faturaları oluşturun, onaylayın, PDF dışa aktarın ve iptal edin",
            "Hata" to "Hata",
            "Fatura Oluştur" to "Fatura Oluştur",
            "PDF Önizleme" to "PDF Önizleme",
            "Kayıtlı Faturalar" to "Kayıtlı Faturalar",
            "Fatura Türü Seçiniz:" to "Fatura Türü Seçiniz:",
            "Satış Faturası (Gelir)" to "Satış Faturası (Gelir)",
            "Alış / Gider Faturası (Gider)" to "Alış / Gider Faturası (Gider)",
            "Fatura Seri / No" to "Fatura Seri / No",
            "Tedarikçi / Satıcı Adı" to "Tedarikçi / Satıcı Adı",
            "Müşteri Adı / Unvanı" to "Müşteri Adı / Unvanı",
            "Örn: Travego Otobüs İşletmeleri A.Ş." to "Örn: Travego Otobüs İşletmeleri A.Ş.",
            "Örn: Ahmet Yılmaz" to "Örn: Ahmet Yılmaz",
            "Vergi No / T.C. Kimlik" to "Vergi No / T.C. Kimlik",
            "Hizmet / Kalem Açıklaması" to "Hizmet / Kalem Açıklaması",
            "Örn: Kapadokya VIP Tur Paket Hizmeti Bedeli" to "Örn: Kapadokya VIP Tur Paket Hizmeti Bedeli",
            "Matrah (KDV Hariç ₺)" to "Matrah (KDV Hariç ₺)",
            "KDV Oranı (%)" to "KDV Oranı (%)",
            "Fatura Notları & Banka Bilgileri" to "Fatura Notları & Banka Bilgileri",
            "Örn: 7 gün içinde ödenmelidir..." to "Örn: 7 gün içinde ödenmelidir...",
            "Kaydediliyor..." to "Kaydediliyor...",
            "Faturayı Veritabanına Kaydet" to "Faturayı Veritabanına Kaydet",
            "GİDER FATURASI" to "GİDER FATURASI",
            "SATIŞ E-FATURASI" to "SATIŞ E-FATURASI",
            "SATICI (TEDARİKÇİ):" to "SATICI (TEDARİKÇİ):",
            "ALICI (MÜŞTERİ):" to "ALICI (MÜŞTERİ):",
            "Vergi / TC No" to "Vergi / TC No",
            "Hizmet / Açıklama" to "Hizmet / Açıklama",
            "Matrah (₺)" to "Matrah (₺)",
            "Turizm Hizmet Bedeli" to "Turizm Hizmet Bedeli",
            "Ara Toplam" to "Ara Toplam",
            "KDV" to "KDV",
            "GENEL TOPLAM" to "GENEL TOPLAM",
            "Not" to "Not",
            "PDF Dışa Aktar & İndir" to "PDF Dışa Aktar & İndir",
            "Tüm Faturalar" to "Tüm Faturalar",
            "Satış / Gelir" to "Satış / Gelir",
            "Alış / Gider" to "Alış / Gider",
            "Henüz kaydedilmiş bir fatura bulunmamaktadır." to "Henüz kaydedilmiş bir fatura bulunmamaktadır.",
            "GİDER" to "GİDER",
            "GELİR" to "GELİR",
            "İPTAL EDİLDİ" to "İPTAL EDİLDİ",
            "Genel Toplam" to "Genel Toplam",

            // CRM & Analytics & Accounts Keys
            "Müşteri Segment Kartları" to "Müşteri Segment Kartları",
            "Tüm Müşteriler" to "Tüm Müşteriler",
            "VIP Sadık Müşteriler" to "VIP Sadık Müşteriler",
            "Yüksek Harcamalı Gezginler" to "Yüksek Harcamalı Gezginler",
            "Yeni Kayıt Olanlar" to "Yeni Kayıt Olanlar",
            "B2B / Kurumsal Temsilciler" to "B2B / Kurumsal Temsilciler",
            "Riskli / Standart Müşteriler" to "Riskli / Standart Müşteriler",
            "Sistemdeki tüm kayıtlı müşteriler ve ciro analizi" to "Sistemdeki tüm kayıtlı müşteriler ve ciro analizi",
            "Çoklu rezervasyonu ve yüksek harcaması olan VIP kitle" to "Çoklu rezervasyonu ve yüksek harcaması olan VIP kitle",
            "LTV ₺10,000+ üstü harcama yapan premium gezginler" to "LTV ₺10,000+ üstü harcama yapan premium gezginler",
            "İlk rezervasyonunu gerçekleştiren yeni müşteriler" to "İlk rezervasyonunu gerçekleştiren yeni müşteriler",
            "Kurumsal acente ve VIP grup yetkilileri" to "Kurumsal acente ve VIP grup yetkilileri",
            "Tekil rezervasyonlu ve destek takibi gereken grup" to "Tekil rezervasyonlu ve destek takibi gereken grup",
            "Canlı Panel Arayüz Dili (Anlık Çeviri)" to "Canlı Panel Arayüz Dili (Anlık Çeviri)",
            "Tüm yönetim panelinin anlık olarak görüntüleneceği dili seçiniz (Tekli seçim)." to "Tüm yönetim panelinin anlık olarak görüntüleneceği dili seçiniz (Tekli seçim).",
            "Acente Web Sitesi Desteklenen Diller (Çoklu Seçim)" to "Acente Web Sitesi Desteklenen Diller (Çoklu Seçim)",
            "Müşterilerinizin acente web sitenizde dil bayrağı menusunde göreceği diller." to "Müşterilerinizin acente web sitenizde dil bayrağı menusunde göreceği diller.",
            "Desteklenen Para Birimleri (Çoklu Seçim)" to "Desteklenen Para Birimleri (Çoklu Seçim)",
            "Sistemde ve web sitesinde müşterilere sunulacak satış ve fiyatlama birimleri." to "Sistemde ve web sitesinde müşterilere sunulacak satış ve fiyatlama birimleri.",
            "Aktif" to "Aktif",
            
            // Dynamic Pricing Rule Engine Keys
            "Dinamik Fiyat Kuralları" to "Dynamic Pricing Rules",
            "Öncelikli kural motoru ve canlı fiyat simülasyon paneli" to "Priority rule engine and live price simulation panel",
            "Öncelik Sıralı Kurallar" to "Priority Ordered Rules",
            "Öncelik Motoru Aktif" to "Priority Engine Active",
            "Canlı Fiyat Simülasyonu" to "Live Price Simulation",
            "SIMULATION LIVE" to "SIMULATION LIVE",
            "Sezon Türü:" to "Sezon Türü:",
            "Acente Seviyesi:" to "Acente Seviyesi:",
            "VIP Acente" to "VIP Acente",
            "Standart" to "Standart",
            "Yüksek Doluluk Artışı (>80%)" to "Yüksek Doluluk Artışı (>80%)",
            "Yüksek Sezon & VIP Acente İndirimi" to "Yüksek Sezon & VIP Acente İndirimi",
            "Almanya / AB Pazarı Özel Tarife" to "Almanya / AB Pazarı Özel Tarife",
            "Düşük Sezon Promosyon Fiyatı" to "Düşük Sezon Promosyon Fiyatı",
            "Kural Listesi" to "Kural Listesi",
            "Fiyat Simülasyonu" to "Fiyat Simülasyonu",
            "ÖNCELİK" to "ÖNCELİK",
            "Doluluk" to "Doluluk",
            "Sezon" to "Sezon",
            "Yüksek" to "Yüksek",
            "Orta" to "Orta",
            "Düşük" to "Düşük",

            // Operator Connections Wizard Keys
            "Bağlı Tur Operatörleri" to "Bağlı Tur Operatörleri",
            "Acente Pazaryeri multi-operatör bağlantı ve komisyon yönetimi" to "Acente Pazaryeri multi-operatör bağlantı ve komisyon yönetimi",
            "Operatör Portföyü & Bağlantılar" to "Operatör Portföyü & Bağlantılar",
            "Sisteminizde tanımlı ve B2B/API entegrasyonlu tur operatörleriniz" to "Sisteminizde tanımlı ve B2B/API entegrasyonlu tur operatörleriniz",
            "Tur Operatörü Ekle" to "Tur Operatörü Ekle",
            "Operatör Arama" to "Operatör Arama",
            "Operatör adı, kodu veya entegrasyon türü ile ara..." to "Operatör adı, kodu veya entegrasyon türü ile ara...",
            "Henüz tanımlanmış bir tur operatörü bulunamadı. Yukarıdaki 'Tur Operatörü Ekle' butonundan ekleyebilirsiniz." to "Henüz tanımlanmış bir tur operatörü bulunamadı. Yukarıdaki 'Tur Operatörü Ekle' butonundan ekleyebilirsiniz.",
            "Operatör Bağlantısını Sil" to "Operatör Bağlantısını Sil",
            "isimli operatör bağlantısını silmek istediğinize emin misiniz?" to "isimli operatör bağlantısını silmek istediğinize emin misiniz?",
            "Satış Kâr Marjı" to "Satış Kâr Marjı",
            "Kar Marjı" to "Kar Marjı",
            "Sabit Ekleme" to "Sabit Ekleme",
            "Hak Edilen Komisyon" to "Hak Edilen Komisyon",
            "Komisyon" to "Komisyon",
            "Düzenle & Detay" to "Düzenle & Detay",
            "Düzenle & Detay" to "Edit & Details",
            "Entegrasyon" to "Integration",
            "Yeni Tur Operatörü Tanımlama Sihirbazı" to "New Tour Operator Creation Wizard",
            "Tur Operatörü Düzenleme" to "Tur Operatörü Düzenleme",
            "Adım" to "Adım",
            "Genel Bilgiler" to "Genel Bilgiler",
            "Fiyat & Komisyon" to "Fiyat & Komisyon",
            "API Entegrasyonu" to "API Entegrasyonu",
            "Muhasebe & Banka" to "Muhasebe & Banka",
            "Temsilci & İletişim" to "Temsilci & İletişim",
            "Operatör Marka & Kimlik Bilgileri" to "Operatör Marka & Kimlik Bilgileri",
            "Operatör Marka Adı *" to "Operatör Marka Adı *",
            "Örn: Coral Travel, Pegas Touristik, ETS Tur" to "Örn: Coral Travel, Pegas Touristik, ETS Tur",
            "Operatör Firma Kodu / ID *" to "Operatör Firma Kodu / ID *",
            "Örn: OP-CORAL-01" to "Örn: OP-CORAL-01",
            "Operatör Türü:" to "Operatör Türü:",
            "Global Operatör" to "Global Operatör",
            "İç Pazar" to "İç Pazar",
            "Yerel DMC" to "Yerel DMC",
            "Bağlantı Durumu:" to "Bağlantı Durumu:",
            "Aktif 🟢" to "Aktif 🟢",
            "Pasif 🟠" to "Pasif 🟠",
            "Fiyatlandırma & Hakediş Parametreleri" to "Fiyatlandırma & Hakediş Parametreleri",
            "Kar Marjı Tipi:" to "Kar Marjı Tipi:",
            "Yüzde (% Kar Eklemeli)" to "Yüzde (% Kar Eklemeli)",
            "Sabit Tutar Ekleme" to "Sabit Tutar Ekleme",
            "Sabit Kar Tutarı" to "Sabit Kar Tutarı",
            "Hak Edilen Komisyon (%)" to "Hak Edilen Komisyon (%)",
            "Çalışma Para Birimi:" to "Çalışma Para Birimi:",
            "B2B & API Entegrasyon Ayarları" to "B2B & API Entegrasyon Ayarları",
            "Entegrasyon Protokolü:" to "Entegrasyon Protokolü:",
            "Operatör API Service URL" to "Operatör API Service URL",
            "Acente API Key / Kodu" to "Acente API Key / Kodu",
            "Fatura & Banka Hesap Detayları" to "Fatura & Banka Hesap Detayları",
            "Operatör Yetkili & İletişim Sorumlusu" to "Operatör Yetkili & İletişim Sorumlusu",
            "Temsilci Adı Soyadı" to "Temsilci Adı Soyadı",
            "Telefon / GSM" to "Telefon / GSM",
            "Kurumsal E-Posta" to "Kurumsal E-Posta",
            "Önceki" to "Önceki",
            "Sonraki" to "Sonraki",
            
            // Financial Reports & Invoice Extra Keys
            "Tüm Şirketler" to "Tüm Şirketler",
            "Merkez Acente" to "Merkez Acente",
            "Antalya Şube" to "Antalya Şube",
            "Aren - Kapadokya Turu Satış Faturası" to "Aren - Kapadokya Turu Satış Faturası",
            "Eda - Kapadokya Turu Satış Faturası" to "Eda - Kapadokya Turu Satış Faturası",
            "Gokhan Azat - Kapadokya Turu Satış Faturası" to "Gokhan Azat - Kapadokya Turu Satış Faturası",
            "whatsap müşterisi - Kapadokya Turu Satış Faturası" to "whatsap müşterisi - Kapadokya Turu Satış Faturası",
            "whatsapp 2 - Kapadokya Turu Satış Faturası" to "whatsapp 2 - Kapadokya Turu Satış Faturası",
            "Tur Tahsilatı" to "Tur Tahsilatı",
            "Fatura Yönetimi & E-Fatura" to "Fatura Yönetimi & E-Fatura",
            "Fatura Türü Seçiniz:" to "Fatura Türü Seçiniz:",
            "Satış Faturası (Gelir)" to "Satış Faturası (Gelir)",
            "Alış / Gider Faturası (Gider)" to "Alış / Gider Faturası (Gider)",
            "Fatura Seri / No" to "Fatura Seri / No",
            "Müşteri Adı / Unvanı" to "Müşteri Adı / Unvanı",
            "Vergi No / T.C. Kimlik" to "Vergi No / T.C. Kimlik",
            "Hizmet / Kalem Açıklaması" to "Hizmet / Kalem Açıklaması",
            "Matrah (KDV Hariç ₺)" to "Matrah (KDV Hariç ₺)",
            "KDV Oranı (%)" to "KDV Oranı (%)",
            "Fatura Notları & Banka Bilgileri" to "Fatura Notları & Banka Bilgileri",
            "NET GENEL BAKİYE" to "NET GENEL BAKİYE",
            "Cari Arama" to "Cari Arama",
            "Cari Adı, Cari Kodu (CAR-...) veya Vergi/TC No ile ara..." to "Cari Adı, Cari Kodu (CAR-...) veya Vergi/TC No ile ara...",
            "Tüm Cariler" to "Tüm Cariler",
            "Toplam" to "Toplam",
            "Müşteri" to "Müşteri",
            "Müşteriler" to "Müşteriler",
            "Henüz sisteme kayıtlı müşteri veya rezervasyon bulunamadı." to "Henüz sisteme kayıtlı müşteri veya rezervasyon bulunamadı.",
            "Gösteriliyor" to "Gösteriliyor",
            "Müşteri Ara..." to "Müşteri Ara...",
            "Bu segmentte veya arama kriterinde müşteri bulunmuyor." to "Bu segmentte veya arama kriterinde müşteri bulunmuyor.",
            "Ort. LTV" to "Ort. LTV",
            "AÇIK" to "AÇIK",
            "Tabloyu Aç" to "Tabloyu Aç",
            "Tamamlanan" to "Tamamlanan",
            "Rezervasyonu" to "Rezervasyonu",
            "Son İşlem" to "Son İşlem",
            "LTV (Toplam Tutar)" to "LTV (Toplam Tutar)",
            "Ara" to "Ara",
            "Son 7 Gün" to "Son 7 Gün",
            "Son 14 Gün" to "Son 14 Gün",
            "Son 30 Gün" to "Son 30 Gün",
            "Operasyonel & Tahmin Analitik Paneli" to "Operasyonel & Tahmin Analitik Paneli",
            "AI Ciro & Gelecek Tahmin Grafiği" to "AI Ciro & Gelecek Tahmin Grafiği",
            "Gerçekleşen satış trendleri ve AI gelecek tahmini" to "Gerçekleşen satış trendleri ve AI gelecek tahmini",
            "Canlı Veri" to "Canlı Veri",
            "Veri Bekleniyor" to "Veri Bekleniyor",
            "Gerçekleşen Ciro" to "Gerçekleşen Ciro",
            "AI Gelecek Tahmini" to "AI Gelecek Tahmini",
            "Seçilen dönemde henüz satış kaydı bulunmamaktadır." to "Seçilen dönemde henüz satış kaydı bulunmamaktadır.",
            "Günlük Satış Hacmi" to "Günlük Satış Hacmi",
            "Dönem İçi Toplam Gerçekleşen Ciro" to "Dönem İçi Toplam Gerçekleşen Ciro",
            "Henüz günlük satış verisi bulunmamaktadır." to "Henüz günlük satış verisi bulunmamaktadır.",
            "Kategori & Operasyon Dağılımı" to "Kategori & Operasyon Dağılımı",
            "Satışların ürün ve hizmet kategorilerine göre oranı" to "Satışların ürün ve hizmet kategorilerine göre oranı",
            "Kategori bazlı satış verisi bulunmamaktadır." to "Kategori bazlı satış verisi bulunmamaktadır.",
            "Rezervasyon" to "Rezervasyon",
            "Satış Kanalı Bazlı Canlı Dağılım" to "Satış Kanalı Bazlı Canlı Dağılım",
            "Gerçekleşen rezervasyonların kanallara göre canlı oranı" to "Gerçekleşen rezervasyonların kanallara göre canlı oranı",
            "Henüz kanal bazlı rezervasyon verisi bulunmamaktadır." to "Henüz kanal bazlı rezervasyon verisi bulunmamaktadır.",
            "Cari Hesap Listesi" to "Cari Hesap Listesi",
            "Filtreye uygun veya veritabanında kaydedilmiş cari hesap bulunamadı." to "Filtreye uygun veya veritabanında kaydedilmiş cari hesap bulunamadı.",
            "NET GENEL BAKİYE" to "NET GENEL BAKİYE",
            "Müşteri Alacakları" to "Müşteri Alacakları",
            "Tedarikçi Borçları" to "Tedarikçi Borçları",
            "Cari Arama" to "Cari Arama",
            "Cari Adı, Cari Kodu (CAR-...) veya Vergi/TC No ile ara..." to "Cari Adı, Cari Kodu (CAR-...) veya Vergi/TC No ile ara...",
            "Tüm Cariler" to "Tüm Cariler",
            "Acenteler" to "Acenteler",
            "Tedarikçiler" to "Tedarikçiler",
            "Borç Toplamı / Alacak Toplamı" to "Borç Toplamı / Alacak Toplamı",
            "Net Bakiye" to "Net Bakiye",
            "Hareket Dökümü & Ekstreyi Aç" to "Hareket Dökümü & Ekstreyi Aç",
            "Cari Hareket Dökümü & Ekstre" to "Cari Hareket Dökümü & Ekstre",
            "Güncel Bakiye:" to "Güncel Bakiye:",
            "Tarih" to "Tarih",
            "Açıklama / Ref" to "Açıklama / Ref",
            "Borç (TL)" to "Borç (TL)",
            "Alacak (TL)" to "Alacak (TL)",
            "Bakiye (TL)" to "Bakiye (TL)",
            "Hareket detayı bulunamadı." to "Hareket detayı bulunamadı.",
            "Kapat" to "Kapat",

            // Expenses & Pricing & Finance Keys
            "Yeni Gider / Tedarikçi Borcu Ekle" to "Yeni Gider / Tedarikçi Borcu Ekle",
            "Gider Kategori / Tedarikçi Türü:" to "Gider Kategori / Tedarikçi Türü:",
            "Oteller" to "Oteller",
            "Araç / Yakıt" to "Araç / Yakıt",
            "Rehber" to "Rehber",
            "Diğer Gider" to "Diğer Gider",
            "Tedarikçi / Alacaklı Adı" to "Tedarikçi / Alacaklı Adı",
            "Gider Tutarı (₺)" to "Gider Tutarı (₺)",
            "Açıklama / Belge No" to "Açıklama / Belge No",
            "Gider Kaydını Veritabanına İşle" to "Gider Kaydını Veritabanına İşle",
            "Otel Borçları" to "Otel Borçları",
            "Araç Borçları" to "Araç Borçları",
            "Rehber Borçları" to "Rehber Borçları",
            "Tüm Tedarikçiler" to "Tüm Tedarikçiler",
            "Araçlar" to "Araçlar",
            "Rehberler" to "Rehberler",
            "Tedarikçi Cari Defteri & Kayıtlı Giderler" to "Tedarikçi Cari Defteri & Kayıtlı Giderler",
            "Henüz veritabanında kaydedilmiş bir gider bulunmamaktadır." to "Henüz veritabanında kaydedilmiş bir gider bulunmamaktadır.",
            "Otel Gideri" to "Otel Gideri",
            "Araç/Yakıt Gideri" to "Araç/Yakıt Gideri",
            "Rehber Gideri" to "Rehber Gideri",
            "Tedarikçi Gideri" to "Tedarikçi Gideri",
            "Ödendi & Giderleşti" to "Ödendi & Giderleşti",
            "Bekleyen Borç" to "Bekleyen Borç",
            "Cari Gider Tutarı" to "Cari Gider Tutarı",
            "Gider Kaydı İşlendi" to "Gider Kaydı İşlendi",
            "Ödeme Yap & İşle" to "Ödeme Yap & İşle",
            "Merkezi PricingEngine Hub" to "Merkezi PricingEngine Hub",
            "B2C Mobil" to "B2C Mobil",
            "B2B Acente" to "B2B Acente",
            "Admin Panel" to "Admin Panel",
            "Kanal Girdi Parametreleri" to "Kanal Girdi Parametreleri",
            "Baz Fiyat (TRY)" to "Baz Fiyat (TRY)",
            "Kişi (Pax)" to "Kişi (Pax)",
            "Kupon Kodu" to "Kupon Kodu",
            "Doluluk Oranı" to "Doluluk Oranı",
            "Merkezi PricingEngine Çıktısı" to "Merkezi PricingEngine Çıktısı",
            "Brüt Toplam Tutar:" to "Brüt Toplam Tutar:",
            "Dinamik Doluluk Ayarlaması:" to "Dinamik Doluluk Ayarlaması:",
            "Kampanya & Kupon İndirimi:" to "Kampanya & Kupon İndirimi:",
            "Acente Hakediş Komisyonu:" to "Acente Hakediş Komisyonu:",
            "Net Tahsil Edilecek Tutar:" to "Net Tahsil Edilecek Tutar:",
            "📑 KDV Raporu" to "📑 KDV Raporu",
            "📈 Gelir / Gider" to "📈 Gelir / Gider",
            "💵 Nakit & Banka" to "💵 Nakit & Banka",
            "📊 Kârlılık Analizi" to "📊 Kârlılık Analizi",
            "Fatura Kes" to "Fatura Kes",
            "Gider Gir" to "Gider Gir",
            "Detaylı Finans Kalemleri Tablosu" to "Detaylı Finans Kalemleri Tablosu",
            "Rapor Filtre Seçenekleri" to "Rapor Filtre Seçenekleri",
            "Firma / Şube:" to "Firma / Şube:",
            "Para Birimi:" to "Para Birimi:",
            "Hesaplanan KDV (Satış)" to "Hesaplanan KDV (Satış)",
            "İndirilecek KDV (Gider)" to "İndirilecek KDV (Gider)",
            "📌 Net Ödenecek / Devreden KDV:" to "📌 Net Ödenecek / Devreden KDV:",
            "Toplam Gelir" to "Toplam Gelir",
            "Toplam Gider" to "Toplam Gider",
            "Net Faaliyet Kârı" to "Net Faaliyet Kârı",
            "Nakit Kasası" to "Nakit Kasası",
            "Banka Hesapları" to "Banka Hesapları",
            "Sanal POS Bekleyen" to "Sanal POS Bekleyen",
            "💰 Toplam Likit Varlıklar:" to "💰 Toplam Likit Varlıklar:",
            "🎯 Ortalama Kâr Marjı:" to "🎯 Ortalama Kâr Marjı:",
            "Açıklama / Kalem" to "Açıklama / Kalem",
            "Matrah" to "Matrah",
            "Henüz kaydedilmiş bir finansal işlem bulunmamaktadır." to "Henüz kaydedilmiş bir finansal işlem bulunmamaktadır."
        ),
        "en" to mapOf(
            // Navigation
            "WEB YÖNETİMİ" to "WEB MANAGEMENT",
            "TUR OPERATÖRLERİ" to "TOUR OPERATORS",
            "MUHASEBE" to "ACCOUNTING",
            "ANALİTİK" to "ANALYTICS",
            "YEREL" to "LOCAL",
            "AYARLAR" to "SETTINGS",
            "Dashboard" to "Dashboard",
            "Turlar" to "Tours",
            "Rezervasyon" to "Bookings",
            "Rezervasyonlar" to "Bookings",
            "Yeni Rezervasyon" to "New Booking",
            "Oteller" to "Hotels",
            "Tur Operatörleri" to "Tour Operators",
            "Ürünler" to "Products",
            "Acente Web Sayfası" to "Agency Website",
            "Fiyat & Kampanya" to "Pricing & Campaigns",
            "Finans" to "Finance",
            "Fatura" to "Invoices",
            "Fatura Yönetimi" to "Invoice Management",
            "Cari Hesap" to "Current Account",
            "Cari Hesaplar" to "Current Accounts",
            "Giderler" to "Expenses",
            "Gider Girişi" to "Expenses",
            "Müşteri & CRM" to "Customer & CRM",
            "Müşteriler & CRM" to "Customers & CRM",
            "TO Cari Hesap" to "TO Current Account",
            "Yerel Tur" to "Local Tour",
            "Yerel Otel" to "Local Hotel",
            "Analitik & Trend" to "Analytics & Trends",
            "Raporlar" to "Reports",
            "Ayarlar & Dil" to "Settings & Language",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "Company & Website Settings",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "Manage agency website logo, header banner, title, slogan and corporate preferences",
            "Ayar Kategorileri" to "Settings Categories",
            "Genel" to "General",
            "Marka" to "Branding",
            "Banka & PayPal" to "Bank & PayPal",
            "Vergi / Sezon" to "Tax / Season",
            "Dil / Para Birimi" to "Language & Currency",
            "Dil ve Para Birimi Tercihleri" to "Language and Currency Preferences",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "Currencies and languages to be actively supported in agency panel and website.",
            "Canlı Panel Arayüz Dili (Anlık Çeviri)" to "Live Panel UI Language (Instant Translation)",
            "Tüm yönetim panelinin anlık olarak görüntüleneceği dili seçiniz (Tekli seçim)." to "Select the primary active language for the management panel (Single selection).",
            "Acente Web Sitesi Desteklenen Diller (Çoklu Seçim)" to "Agency Website Supported Languages (Multi-Selection)",
            "Müşterilerinizin acente web sitenizde dil bayrağı menusunde göreceği diller." to "Languages displayed in the flag menu on your agency website.",
            "Desteklenen Para Birimleri (Çoklu Seçim)" to "Supported Currencies (Multi-Selection)",
            "Sistemde ve web sitesinde müşterilere sunulacak satış ve fiyatlama birimleri." to "Sales and pricing currencies offered to customers in system and website.",
            "Desteklenen Para Birimleri" to "Supported Currencies",
            "Desteklenen Panel Dilleri" to "Supported Panel Languages",
            "Değişiklikleri Kaydet ✓" to "Save Changes ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "Tour Catalog",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "Manage your active tours, packages and routes",
            "+ Yeni Tur Ekle" to "+ Add New Tour",
            "Tur adı, tur kodu veya şehir ile ara..." to "Search by tour name, code or city...",
            "Tüm Kategoriler" to "All Categories",
            "Günübirlik Tur" to "Day Trip",
            "Kültür Turu" to "Cultural Tour",
            "Macera & Doğa" to "Adventure & Nature",
            "Gemi & Cruise" to "Cruise & Ship",
            "VIP Özel Tur" to "VIP Private Tour",
            "Transfer Hizmeti" to "Transfer Service",
            "Tümü" to "All",
            "Aktif" to "Active",
            "Pasif" to "Passive",
            "Düzenle" to "Edit",
            "TUR KODU & ADI" to "TOUR CODE & NAME",
            "KATEGORİ" to "CATEGORY",
            "LOKASYON & SÜRE" to "LOCATION & DURATION",
            "DURUM" to "STATUS",
            "İŞLEM" to "ACTION",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "Tour & Hotel Search Engine",
            "Kalkış Şehri (Nereden)" to "Departure City (From)",
            "Nereye (Ülke / Bölge / Otel)" to "Destination (Country / Region / Hotel)",
            "Tur Operatörü Filtresi" to "Tour Operator Filter",
            "Maks. Bütçe (₺)" to "Max Budget ($)",
            "TURLARI ARA 🔍" to "SEARCH TOURS 🔍",
            "Hızlı Operatör Filtresi:" to "Quick Operator Filter:",
            "Tüm Operatörler" to "All Operators",
            "Tümünü Göster ➔" to "Show All ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "Custom tour packages created by the agency.",
            "Tüm Tur Paketleri" to "All Tour Packages",
            "Seçili Oteller" to "Selected Hotels",
            "İncele" to "Review",
            "Detaylar" to "Details",
            "Paket Turlar" to "Package Tours",
            "Gezginler Tarafından Onaylanmış Her Şey Dahil Paket Turlar" to "Traveler-Approved All-Inclusive Package Tours",
            "Oteller" to "Hotels",
            "Ayrıcalıklı konaklama ve seçkin 5 yıldızlı oteller" to "Exclusive accommodation and elite 5-star hotels",
            "Son Dakika" to "Last Minute",
            "Acele edin ve %70'e varan muhteşem indirimlerden yararlanın!" to "Hurry up and enjoy amazing discounts up to 70%!",
            "Charter & Tarifeli Uçuşlar" to "Charter & Scheduled Flights",
            "En uygun fiyatlı direkt charter uçuşlar ve özel havayolu biletleri" to "Best value direct charter flights and special airline tickets",
            "Bulunan Arama Fırsatları" to "Search Deals Found",
            "Kriterlerinize uyan en uygun fiyatlı canlı tur ve otel teklifleri" to "Best price live tour and hotel offers matching your criteria",
            "İNDİRİM" to "OFF",
            "Charter Uçuş Seferi" to "Charter Flight",
            "Direkt Uçuş" to "Direct Flight",
            "Operatör Teklifi" to "Operator Offer",
            "Gece" to "Night(s)",
            "En Düşük Fiyat" to "Lowest Price",
            "En Yüksek Fiyat" to "Highest Price",
            "Tur Paketi" to "Tour Package",
            "Uçuşlar" to "Flights",
            "Destinasyon" to "Destination",
            "Nereye (Destinasyon / Ülke)" to "Destination (To / Country)",
            "Tek Yön" to "One Way",
            "Gidiş & Dönüş" to "Round Trip",
            "Gidiş Tarihi" to "Departure Date",
            "Dönüş Tarihi" to "Return Date",
            "Dönüş Ekleyin" to "Add Return Date",
            "Tarih" to "Date",
            "Gidiş Başlangıç" to "Departure Start",
            "Gidiş Bitiş" to "Departure End",
            "Opsiyon" to "Option",
            "Gece Sayısı" to "Number of Nights",
            "Turist Sayısı" to "Number of Tourists",
            "Tur Operatörü" to "Tour Operator",
            "Tüm Operatörler" to "All Operators",
            "Ülke" to "Country",
            "Türkiye" to "Turkey",
            "Tüm Ülkeler" to "All Countries",
            "ARAMA BAŞLAT" to "START SEARCH",
            "3 Gece" to "3 Nights",
            "5 Gece" to "5 Nights",
            "7 Gece" to "7 Nights",
            "10 Gece" to "10 Nights",
            "14 Gece" to "14 Nights",
            "1 Yetişkin" to "1 Adult",
            "2 Yetişkin" to "2 Adults",
            "3 Yetişkin" to "3 Adults",
            "2 Yetişkin + 1 Çocuk" to "2 Adults + 1 Child",
            "2 Yetişkin + 2 Çocuk" to "2 Adults + 2 Children",
            
            // Operational Screens
            "Operasyon Dashboard" to "Operations Dashboard",
            "Rol" to "Role",
            "Canlı İşletme & Operasyon Özeti" to "Live Business & Operations Summary",
            "Çıkış Yap" to "Log Out",
            "Rezervasyon Yönetimi" to "Booking Management",
            "Tüm turlarındaki rezervasyon taleplerini ve durumlarını takip edin" to "Track booking requests and statuses of all tours",
            "+ Yeni Rezervasyon" to "+ New Booking",
            "Otel Portföy Yönetimi" to "Hotel Portfolio Management",
            "Konaklama tesislerini, kontrat şartlarını ve otel bilgilerini yönetin" to "Manage accommodation facilities, contract terms and hotel details",
            "+ Yeni Otel Ekle" to "+ Add New Hotel",
            "Finansal Raporlar & Analizler" to "Financial Reports & Analytics",
            "KDV, Gelir-Gider, Likidite ve Kârlılık Dökümleri" to "VAT, Income-Expense, Liquidity and Profitability Statements",
            "Cari Hesaplar & Mutabakat" to "Current Accounts & Reconciliation",
            "Müşteri, acente ve tedarikçi bakiye dökümleri ve ekstreler" to "Customer, agency and supplier balance statements and extracts",
            "Tedarikçi Cari & Gider Girişi" to "Supplier Account & Expense Entry",
            "Otel, araç yakıt ve rehber gider akışları ve cari takibi" to "Hotel, vehicle fuel and guide expense flows and account tracking",
            "Müşteri Segmentleri & CRM" to "Customer Segments & CRM",
            "Kullanıcı davranışlarına göre canlı segmentasyon ve müşteri dökümü" to "Live segmentation and customer breakdown based on user behavior",
            "Analitik & Tahmin Grafikleri" to "Analytics & Forecast Charts",
            "Gerçekleşen satış trendleri ve AI gelecek tahmin analizi" to "Actual sales trends and AI future forecast analysis",
            "📊 Raporlar & Analitik Merkezi" to "📊 Reports & Analytics Hub",
            "Filtreli operasyon, otel, tur operatörü satış ve finansal çıktılar" to "Filtered operational, hotel, tour operator sales and financial outputs",
            "Toplam" to "Total",
            "Müşteri" to "Customer",
            "Müşteriler" to "Customers",
            "Henüz sisteme kayıtlı müşteri veya rezervasyon bulunamadı." to "No registered customers or bookings found yet.",
            "Gösteriliyor" to "Showing",
            "Müşteri Ara..." to "Search Customer...",
            "Bu segmentte veya arama kriterinde müşteri bulunmuyor." to "No customers found in this segment or search criteria.",
            "Ort. LTV" to "Avg. LTV",
            "AÇIK" to "OPEN",
            "Tabloyu Aç" to "Open Table",
            "Tamamlanan" to "Completed",
            "Rezervasyonu" to "Bookings",
            "Son İşlem" to "Last Transaction",
            "LTV (Toplam Tutar)" to "LTV (Total Value)",
            "Ara" to "Call",
            "Son 7 Gün" to "Last 7 Days",
            "Son 14 Gün" to "Last 14 Days",
            "Son 30 Gün" to "Last 30 Days",
            "Operasyonel & Tahmin Analitik Paneli" to "Operational & Forecast Analytics Panel",
            "AI Ciro & Gelecek Tahmin Grafiği" to "AI Revenue & Future Forecast Chart",
            "Gerçekleşen satış trendleri ve AI gelecek tahmini" to "Actual sales trends and AI future forecast",
            "Canlı Veri" to "Live Data",
            "Veri Bekleniyor" to "Awaiting Data",
            "Gerçekleşen Ciro" to "Actual Revenue",
            "AI Gelecek Tahmini" to "AI Future Forecast",
            "Seçilen dönemde henüz satış kaydı bulunmamaktadır." to "No sales records found in selected period.",
            "Günlük Satış Hacmi" to "Daily Sales Volume",
            "Dönem İçi Toplam Gerçekleşen Ciro" to "Total Revenue Realized in Period",
            "Henüz günlük satış verisi bulunmamaktadır." to "No daily sales data available yet.",
            "Kategori & Operasyon Dağılımı" to "Category & Operation Breakdown",
            "Satışların ürün ve hizmet kategorilerine göre oranı" to "Ratio of sales by product and service category",
            "Kategori bazlı satış verisi bulunmamaktadır." to "No category-based sales data available.",
            "Rezervasyon" to "Bookings",
            "Satış Kanalı Bazlı Canlı Dağılım" to "Live Breakdown by Sales Channel",
            "Gerçekleşen rezervasyonların kanallara göre canlı oranı" to "Live ratio of realized bookings by channel",
            "Henüz kanal bazlı rezervasyon verisi bulunmamaktadır." to "No channel-based booking data available yet.",
            "Cari Hesap Listesi" to "Current Account List",
            "Filtreye uygun veya veritabanında kaydedilmiş cari hesap bulunamadı." to "No current accounts found matching filter or database.",
            "NET GENEL BAKİYE" to "NET OVERALL BALANCE",
            "Müşteri Alacakları" to "Customer Receivables",
            "Tedarikçi Borçları" to "Supplier Payables",
            "Cari Arama" to "Account Search",
            "Cari Adı, Cari Kodu (CAR-...) veya Vergi/TC No ile ara..." to "Search by Name, Code (CAR-...) or Tax ID...",
            "Tüm Cariler" to "All Accounts",
            "Acenteler" to "Agencies",
            "Tedarikçiler" to "Suppliers",
            "Borç Toplamı / Alacak Toplamı" to "Total Debit / Total Credit",
            "Net Bakiye" to "Net Balance",
            "Hareket Dökümü & Ekstreyi Aç" to "Open Transaction Statement",
            "Cari Hareket Dökümü & Ekstre" to "Account Statement & Ledger",
            "Güncel Bakiye:" to "Current Balance:",
            "Tarih" to "Date",
            "Açıklama / Ref" to "Description / Ref",
            "Borç (TL)" to "Debit ($)",
            "Alacak (TL)" to "Credit ($)",
            "Bakiye (TL)" to "Balance ($)",
            "Hareket detayı bulunamadı." to "No transaction details found.",
            "Kapat" to "Close",

            // Expenses & Pricing & Finance Keys
            "Yeni Gider / Tedarikçi Borcu Ekle" to "Add New Expense / Supplier Debt",
            "Gider Kategori / Tedarikçi Türü:" to "Expense Category / Supplier Type:",
            "Oteller" to "Hotels",
            "Araç / Yakıt" to "Vehicle / Fuel",
            "Rehber" to "Guide",
            "Diğer Gider" to "Other Expense",
            "Tedarikçi / Alacaklı Adı" to "Supplier / Creditor Name",
            "Gider Tutarı (₺)" to "Expense Amount ($)",
            "Açıklama / Belge No" to "Description / Document No",
            "Gider Kaydını Veritabanına İşle" to "Process Expense to Database",
            "Otel Borçları" to "Hotel Debts",
            "Araç Borçları" to "Vehicle Debts",
            "Rehber Borçları" to "Guide Debts",
            "Tüm Tedarikçiler" to "All Suppliers",
            "Araçlar" to "Vehicles",
            "Rehberler" to "Guides",
            "Tedarikçi Cari Defteri & Kayıtlı Giderler" to "Supplier Ledger & Saved Expenses",
            "Henüz veritabanında kaydedilmiş bir gider bulunmamaktadır." to "No saved expenses found in database yet.",
            "Otel Gideri" to "Hotel Expense",
            "Araç/Yakıt Gideri" to "Vehicle/Fuel Expense",
            "Rehber Gideri" to "Guide Expense",
            "Tedarikçi Gideri" to "Supplier Expense",
            "Ödendi & Giderleşti" to "Paid & Expensed",
            "Bekleyen Borç" to "Pending Debt",
            "Cari Gider Tutarı" to "Ledger Expense Amount",
            "Gider Kaydı İşlendi" to "Expense Processed",
            "Ödeme Yap & İşle" to "Make Payment & Process",
            "Merkezi PricingEngine Hub" to "Central PricingEngine Hub",
            "B2C Mobil" to "B2C Mobile",
            "B2B Acente" to "B2B Agency",
            "Admin Panel" to "Admin Panel",
            "Kanal Girdi Parametreleri" to "Channel Input Parameters",
            "Baz Fiyat (TRY)" to "Base Price ($)",
            "Kişi (Pax)" to "Pax Count",
            "Kupon Kodu" to "Coupon Code",
            "Doluluk Oranı" to "Occupancy Rate",
            "Merkezi PricingEngine Çıktısı" to "Central PricingEngine Output",
            "Brüt Toplam Tutar:" to "Gross Total Amount:",
            "Dinamik Doluluk Ayarlaması:" to "Dynamic Occupancy Adjustment:",
            "Kampanya & Kupon İndirimi:" to "Campaign & Coupon Discount:",
            "Acente Hakediş Komisyonu:" to "Agency Earned Commission:",
            "Net Tahsil Edilecek Tutar:" to "Net Amount to Collect:",
            "📑 KDV Raporu" to "📑 VAT Report",
            "📈 Gelir / Gider" to "📈 Income / Expense",
            "💵 Nakit & Banka" to "💵 Cash & Bank",
            "📊 Kârlılık Analizi" to "📊 Profitability Analysis",
            "Fatura Kes" to "Issue Invoice",
            "Gider Gir" to "Add Expense",
            "Detaylı Finans Kalemleri Tablosu" to "Detailed Financial Items Table",
            "Rapor Filtre Seçenekleri" to "Report Filter Options",
            "Firma / Şube:" to "Company / Branch:",
            "Para Birimi:" to "Currency:",
            "Hesaplanan KDV (Satış)" to "Output VAT (Sales)",
            "İndirilecek KDV (Gider)" to "Input VAT (Expense)",
            "📌 Net Ödenecek / Devreden KDV:" to "📌 Net VAT Payable / Deferred:",
            "Toplam Gelir" to "Total Revenue",
            "Toplam Gider" to "Total Expenses",
            "Net Faaliyet Kârı" to "Net Operating Profit",
            "Nakit Kasası" to "Cash Register",
            "Banka Hesapları" to "Bank Accounts",
            "Sanal POS Bekleyen" to "Pending POS",
            "💰 Toplam Likit Varlıklar:" to "Total Liquid Assets:",
            "🎯 Ortalama Kâr Marjı:" to "Average Profit Margin:",
            "Açıklama / Kalem" to "Description / Item",
            "Matrah" to "Subtotal",
            "Henüz kaydedilmiş bir finansal işlem bulunmamaktadır." to "No saved financial transactions found yet."
        ),
        "de" to mapOf(
            // Navigation
            "WEB YÖNETİMİ" to "WEB-VERWALTUNG",
            "TUR OPERATÖRLERİ" to "REISEVERANSTALTER",
            "MUHASEBE" to "BUCHHALTUNG",
            "ANALİTİK" to "ANALYTIK",
            "YEREL" to "LOKAL",
            "AYARLAR" to "EINSTELLUNGEN",
            "Dashboard" to "Dashboard",
            "Turlar" to "Touren",
            "Rezervasyon" to "Buchungen",
            "Rezervasyonlar" to "Buchungen",
            "Yeni Rezervasyon" to "Neue Buchung",
            "Oteller" to "Hotels",
            "Tur Operatörleri" to "Reiseveranstalter",
            "Ürünler" to "Produkte",
            "Acente Web Sayfası" to "Agentur Webseite",
            "Fiyat & Kampanya" to "Preise & Aktionen",
            "Finans" to "Finanzen",
            "Fatura" to "Rechnungen",
            "Fatura Yönetimi" to "Rechnungsverwaltung",
            "Cari Hesap" to "Laufendes Konto",
            "Cari Hesaplar" to "Laufende Konten",
            "Giderler" to "Ausgaben",
            "Gider Girişi" to "Ausgaben",
            "Müşteri & CRM" to "Kunden & CRM",
            "Müşteriler & CRM" to "Kunden & CRM",
            "TO Cari Hesap" to "RV Laufendes Konto",
            "Yerel Tur" to "Lokale Tour",
            "Yerel Otel" to "Lokales Hotel",
            "Analitik & Trend" to "Analytik & Trends",
            "Raporlar" to "Berichte",
            "Ayarlar & Dil" to "Einstellungen & Sprache",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "Unternehmenseinstellungen",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "Verwalten Sie Logo, Header-Banner, Titel, Slogan und Präferenzen der Agentur",
            "Ayar Kategorileri" to "Einstellungskategorien",
            "Genel" to "Allgemein",
            "Marka" to "Marke",
            "Banka & PayPal" to "Bank & PayPal",
            "Vergi / Sezon" to "Steuer / Saison",
            "Dil / Para Birimi" to "Sprache & Währung",
            "Dil ve Para Birimi Tercihleri" to "Sprach- und Währungseinstellungen",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "Aktiv unterstützte Währungen und Sprachen im Agenturpanel und auf der Website.",
            "Desteklenen Para Birimleri" to "Unterstützte Währungen",
            "Desteklenen Panel Dilleri" to "Unterstützte Panelsprachen",
            "Değişiklikleri Kaydet ✓" to "Änderungen Speichern ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "Tourenkatalog",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "Verwalten Sie Ihre aktiven Touren, Pakete und Routen",
            "+ Yeni Tur Ekle" to "+ Neue Tour Hinzufügen",
            "Tur adı, tur kodu veya şehir ile ara..." to "Suchen Sie nach Tourname, Code oder Stadt...",
            "Tüm Kategoriler" to "Alle Kategorien",
            "Günübirlik Tur" to "Tagesausflug",
            "Kültür Turu" to "Kulturtour",
            "Macera & Doğa" to "Abenteuer & Natur",
            "Gemi & Cruise" to "Kreuzfahrt & Schiff",
            "VIP Özel Tur" to "VIP Private Tour",
            "Transfer Hizmeti" to "Transferservice",
            "Tümü" to "Alle",
            "Aktif" to "Aktiv",
            "Pasif" to "Inaktiv",
            "Düzenle" to "Bearbeiten",
            "TUR KODU & ADI" to "TOUR-CODE & NAME",
            "KATEGORİ" to "KATEGORIE",
            "LOKASYON & SÜRE" to "STANDORT & DAUER",
            "DURUM" to "STATUS",
            "İŞLEM" to "AKTION",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "Tour- & Hotelsuchmaschine",
            "Kalkış Şehri (Nereden)" to "Abfahrtsort (Von)",
            "Nereye (Ülke / Bölge / Otel)" to "Zielort (Land / Region / Hotel)",
            "Tur Operatörü Filtresi" to "Reiseveranstalter-Filter",
            "Maks. Bütçe (₺)" to "Max. Budget (€)",
            "TURLARI ARA 🔍" to "TOUREN SUCHEN 🔍",
            "Hızlı Operatör Filtresi:" to "Schnellfilter:",
            "Tüm Operatörler" to "Alle Veranstalter",
            "Tümünü Göster ➔" to "Alle Anzeigen ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "Maßgeschneiderte Tourpakete der Agentur.",
            "Tüm Tur Paketleri" to "Alle Tourpakete",
            "Seçili Oteller" to "Ausgewählte Hotels",
            "İncele" to "Überprüfen",
            "Detaylar" to "Details",
            "Paket Turlar" to "Pauschalreisen",
            "Gezginler Tarafından Onaylanmış Her Şey Dahil Paket Turlar" to "Von Reisenden geprüfte All-Inclusive-Pauschalreisen",
            "Oteller" to "Hotels",
            "Ayrıcalıklı konaklama ve seçkin 5 yıldızlı oteller" to "Exklusive Unterkünfte und ausgewählte 5-Sterne-Hotels",
            "Son Dakika" to "Last Minute",
            "Acele edin ve %70'e varan muhteşem indirimlerden yararlanın!" to "Beeilen Sie sich und genießen Sie Rabatte von bis zu 70%!",
            "Charter & Tarifeli Uçuşlar" to "Charter- & Linienflüge",
            "En uygun fiyatlı direkt charter uçuşlar ve özel havayolu biletleri" to "Günstigste Direkt-Charterflüge und spezielle Flugtickets",
            "Bulunan Arama Fırsatları" to "Gefundene Suchangebote",
            "Kriterlerinize uyan en uygun fiyatlı canlı tur ve otel teklifleri" to "Beste Live-Tour- und Hotelangebote nach Ihren Kriterien",
            "İNDİRİM" to "RABATT",
            "Charter Uçuş Seferi" to "Charterflug",
            "Direkt Uçuş" to "Direktflug",
            "Operatör Teklifi" to "Veranstalter-Angebot",
            "Gece" to "Nächte",
            "En Düşük Fiyat" to "Günstigster Preis",
            "En Yüksek Fiyat" to "Höchster Preis",
            "Tur Paketi" to "Pauschalreise",
            "Uçuşlar" to "Flüge",
            "Destinasyon" to "Reiseziel",
            "Nereye (Destinasyon / Ülke)" to "Zielort (Nach / Land)",
            "Tek Yön" to "Hinflug",
            "Gidiş & Dönüş" to "Hin- & Rückflug",
            "Gidiş Tarihi" to "Hinflugdatum",
            "Dönüş Tarihi" to "Rückflugdatum",
            "Dönüş Ekleyin" to "Rückflug hinzufügen",
            "Tarih" to "Datum",
            "Gidiş Başlangıç" to "Abreise Beginn",
            "Gidiş Bitiş" to "Abreise Ende",
            "Opsiyon" to "Option",
            "Gece Sayısı" to "Anzahl der Nächte",
            "Turist Sayısı" to "Anzahl der Touristen",
            "Tur Operatörü" to "Reiseveranstalter",
            "Tüm Operatörler" to "Alle Veranstalter",
            "Ülke" to "Land",
            "Türkiye" to "Türkei",
            "Tüm Ülkeler" to "Alle Länder",
            "ARAMA BAŞLAT" to "SUCHE STARTEN",
            "3 Gece" to "3 Nächte",
            "5 Gece" to "5 Nächte",
            "7 Gece" to "7 Nächte",
            "10 Gece" to "10 Nächte",
            "14 Gece" to "14 Nächte",
            "1 Yetişkin" to "1 Erwachsener",
            "2 Yetişkin" to "2 Erwachsene",
            "3 Yetişkin" to "3 Erwachsene",
            "2 Yetişkin + 1 Çocuk" to "2 Erwachsene + 1 Kind",
            "2 Yetişkin + 2 Çocuk" to "2 Erwachsene + 2 Kinder",
        ),
        "ru" to mapOf(
            // Navigation
            "WEB YÖNETİMİ" to "ВЕБ-УПРАВЛЕНИЕ",
            "TUR OPERATÖRLERİ" to "ТУРОПЕРАТОРЫ",
            "MUHASEBE" to "БУХГАЛТЕРИЯ",
            "ANALİTİK" to "АНАЛИТИКА",
            "YEREL" to "МЕСТНЫЕ",
            "AYARLAR" to "НАСТРОЙКИ",
            "Dashboard" to "Дашборд",
            "Turlar" to "Туры",
            "Rezervasyon" to "Бронирования",
            "Rezervasyonlar" to "Бронирования",
            "Yeni Rezervasyon" to "Новое бронирование",
            "Oteller" to "Отели",
            "Tur Operatörleri" to "Туроператоры",
            "Ürünler" to "Продукты",
            "Acente Web Sayfası" to "Сайт агентства",
            "Fiyat & Kampanya" to "Цены и акции",
            "Finans" to "Финансы",
            "Fatura" to "Счета",
            "Fatura Yönetimi" to "Управление счетами",
            "Cari Hesap" to "Текущий счет",
            "Cari Hesaplar" to "Текущие счета",
            "Giderler" to "Расходы",
            "Gider Girişi" to "Расходы",
            "Müşteri & CRM" to "Клиенты и CRM",
            "Müşteriler & CRM" to "Клиенты и CRM",
            "TO Cari Hesap" to "ТО Текущий счет",
            "Yerel Tur" to "Местный тур",
            "Yerel Otel" to "Местный отель",
            "Analitik & Trend" to "Аналитика и тренды",
            "Raporlar" to "Отчеты",
            "Ayarlar & Dil" to "Настройки и язык",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "Настройки компании",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "Управление логотипом, банером, заголовком, слоганом и настройками сайта",
            "Ayar Kategorileri" to "Категории настроек",
            "Genel" to "Общие",
            "Marka" to "Брендинг",
            "Banka & PayPal" to "Банк и PayPal",
            "Vergi / Sezon" to "Налоги / Сезон",
            "Dil / Para Birimi" to "Язык и валюта",
            "Dil ve Para Birimi Tercihleri" to "Настройки языка и валюты",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "Валюты и языки, поддерживаемые в панели агентства и на сайте.",
            "Desteklenen Para Birimleri" to "Поддерживаемые валюты",
            "Desteklenen Panel Dilleri" to "Поддерживаемые языки панели",
            "Değişiklikleri Kaydet ✓" to "Сохранить изменения ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "Каталог туров",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "Управление турами, пакетами и маршрутами",
            "+ Yeni Tur Ekle" to "+ Добавить тур",
            "Tur adı, tur kodu veya şehir ile ara..." to "Поиск по названию, коду или городу...",
            "Tüm Kategoriler" to "Все категории",
            "Günübirlik Tur" to "Однодневный тур",
            "Kültür Turu" to "Экскурсионный тур",
            "Macera & Doğa" to "Приключения и природа",
            "Gemi & Cruise" to "Круиз",
            "VIP Özel Tur" to "VIP тур",
            "Transfer Hizmeti" to "Трансфер",
            "Tümü" to "Все",
            "Aktif" to "Активные",
            "Pasif" to "Неактивные",
            "Düzenle" to "Изменить",
            "TUR KODU & ADI" to "КОД И НАЗВАНИЕ ТУРА",
            "KATEGORİ" to "КАТЕГОРИЯ",
            "LOKASYON & SÜRE" to "ЛОКАЦИЯ И ДЛИТЕЛЬНОСТЬ",
            "DURUM" to "СТАТУС",
            "İŞLEM" to "ДЕЙСТВИЕ",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "Поиск туров и отелей",
            "Kalkış Şehri (Nereden)" to "Город вылета (Откуда)",
            "Nereye (Ülke / Bölge / Otel)" to "Направление (Куда)",
            "Tur Operatörü Filtresi" to "Фильтр туроператоров",
            "Maks. Bütçe (₺)" to "Макс. бюджет (₽)",
            "TURLARI ARA 🔍" to "ИСКАТЬ ТУРЫ 🔍",
            "Hızlı Operatör Filtresi:" to "Быстрый фильтр:",
            "Tüm Operatörler" to "Все туроператоры",
            "Tümünü Göster ➔" to "Показать все ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "Специальные туры агентства.",
            "Tüm Tur Paketleri" to "Все туры",
            "Seçili Oteller" to "Отели",
            "İncele" to "Просмотр",
            "Detaylar" to "Детали",
            "Paket Turlar" to "Пакетные туры",
            "Gezginler Tarafından Onaylanmış Her Şey Dahil Paket Turlar" to "Одобренные путешественниками туры «Все включено»",
            "Oteller" to "Отели",
            "Ayrıcalıklı konaklama ve seçkin 5 yıldızlı oteller" to "Эксклюзивное проживание и элитные 5-звездочные отели",
            "Son Dakika" to "Горящие туры",
            "Acele edin ve %70'e varan muhteşem indirimlerden yararlanın!" to "Поспешите и получите потрясающие скидки до 70%!",
            "Charter & Tarifeli Uçuşlar" to "Чартерные и регулярные рейсы",
            "En uygun fiyatlı direkt charter uçuşlar ve özel havayolu biletleri" to "Самые выгодные прямые чартерные рейсы и авиабилеты",
            "Bulunan Arama Fırsatları" to "Найденные варианты",
            "Kriterlerinize uyan en uygun fiyatlı canlı tur ve otel teklifleri" to "Лучшие предложения туров и отелей по вашим критериям",
            "İNDİRİM" to "СКИДКА",
            "Charter Uçuş Seferi" to "Чартерный рейс",
            "Direkt Uçuş" to "Прямой рейс",
            "Operatör Teklifi" to "Предложение оператора",
            "Gece" to "Ночей",
            "En Düşük Fiyat" to "Мин. цена",
            "En Yüksek Fiyat" to "Макс. цена",
            "Tur Paketi" to "Пакетный тур",
            "Uçuşlar" to "Перелеты",
            "Destinasyon" to "Направление",
            "Nereye (Destinasyon / Ülke)" to "Направление (Куда / Страна)",
            "Tek Yön" to "В одну сторону",
            "Gidiş & Dönüş" to "Туда и обратно",
            "Gidiş Tarihi" to "Дата вылета",
            "Dönüş Tarihi" to "Дата возврата",
            "Dönüş Ekleyin" to "Добавить обратный рейс",
            "Tarih" to "Дата",
            "Gidiş Başlangıç" to "Начало вылета",
            "Gidiş Bitiş" to "Конец вылета",
            "Opsiyon" to "Опции",
            "Gece Sayısı" to "Количество ночей",
            "Turist Sayısı" to "Количество туристов",
            "Tur Operatörü" to "Туроператор",
            "Tüm Operatörler" to "Все туроператоры",
            "Ülke" to "Страна",
            "Türkiye" to "Турция",
            "Tüm Ülkeler" to "Все страны",
            "ARAMA BAŞLAT" to "НАЧАТЬ ПОИСК",
            "3 Gece" to "3 Ночи",
            "5 Gece" to "5 Ночей",
            "7 Gece" to "7 Ночей",
            "10 Gece" to "10 Ночей",
            "14 Gece" to "14 Ночей",
            "1 Yetişkin" to "1 Взрослый",
            "2 Yetişkin" to "2 Взрослых",
            "3 Yetişkin" to "3 Взрослых",
            "2 Yetişkin + 1 Çocuk" to "2 Взрослых + 1 Ребенок",
            "2 Yetişkin + 2 Çocuk" to "2 Взрослых + 2 Детей",
        ),
        "ar" to mapOf(
            // Navigation
            "WEB YÖNETİMİ" to "إدارة الويب",
            "TUR OPERATÖRLERİ" to "منظمو الرحلات",
            "MUHASEBE" to "المحاسبة",
            "ANALİTİK" to "التحليلات",
            "YEREL" to "محلي",
            "AYARLAR" to "الإعدادات",
            "Dashboard" to "لوحة التحكم",
            "Turlar" to "الجولات",
            "Rezervasyon" to "الحجوزات",
            "Rezervasyonlar" to "الحجوزات",
            "Yeni Rezervasyon" to "حجز جديد",
            "Oteller" to "الفنادق",
            "Tur Operatörleri" to "منظمو الرحلات",
            "Ürünler" to "المنتجات",
            "Acente Web Sayfası" to "موقع الوكالة",
            "Fiyat & Kampanya" to "الأسعار والعروض",
            "Finans" to "المالية",
            "Fatura" to "الفواتير",
            "Fatura Yönetimi" to "إدارة الفواتير",
            "Cari Hesap" to "الحساب الجاري",
            "Cari Hesaplar" to "الحسابات الجارية",
            "Giderler" to "المصروفات",
            "Gider Girişi" to "المصروفات",
            "Müşteri & CRM" to "العملاء و CRM",
            "Müşteriler & CRM" to "العملاء و CRM",
            "TO Cari Hesap" to "الحساب الجاري للشركة",
            "Yerel Tur" to "جولة محلية",
            "Yerel Otel" to "فندق محلي",
            "Analitik & Trend" to "التحليلات والاتجاهات",
            "Raporlar" to "التقارير",
            "Ayarlar & Dil" to "الإعدادات واللغة",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "إعدادات الشركة والموقع",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "إدارة شعار الموقع والعناوين والتفضيلات المؤسسية",
            "Ayar Kategorileri" to "فئات الإعدادات",
            "Genel" to "عام",
            "Marka" to "العلامة التجارية",
            "Banka & PayPal" to "البنك و PayPal",
            "Vergi / Sezon" to "الضرائب / الموسم",
            "Dil / Para Birimi" to "اللغة والعملة",
            "Dil ve Para Birimi Tercihleri" to "تفضيلات اللغة والعملة",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "العملات واللغات المدعومة في لوحة الوكالة والموقع الإلكتروني.",
            "Desteklenen Para Birimleri" to "العملات المدعومة",
            "Desteklenen Panel Dilleri" to "لغات اللوحة المدعومة",
            "Değişiklikleri Kaydet ✓" to "حفظ التغييرات ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "كتالوج الجولات",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "إدارة الجولات والمسارات النشطة",
            "+ Yeni Tur Ekle" to "+ إضافة جولة جديدة",
            "Tur adı, tur kodu veya şehir ile ara..." to "البحث حسب الاسم أو الرمز أو المدينة...",
            "Tüm Kategoriler" to "جميع الفئات",
            "Günübirlik Tur" to "جولة يومية",
            "Kültür Turu" to "جولة ثقافية",
            "Macera & Doğa" to "المغامرة والطبيعة",
            "Gemi & Cruise" to "رحلة بحرية",
            "VIP Özel Tur" to "جولة VIP خاصة",
            "Transfer Hizmeti" to "خدمة النقل",
            "Tümü" to "الكل",
            "Aktif" to "نشط",
            "Pasif" to "غير نشط",
            "Düzenle" to "تعديل",
            "TUR KODU & ADI" to "رمز واسم الجولة",
            "KATEGORİ" to "الفئة",
            "LOKASYON & SÜRE" to "الموقع والمدة",
            "DURUM" to "الحالة",
            "İŞLEM" to "الإجراء",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "محرك بحث الجولات والفنادق",
            "Kalkış Şehri (Nereden)" to "مدينة المغادرة (من)",
            "Nereye (Ülke / Bölge / Otel)" to "الوجهة (إلى)",
            "Tur Operatörü Filtresi" to "فلتر منظم الرحلات",
            "Maks. Bütçe (₺)" to "الحد الأقصى للميزانية ($)",
            "TURLARI ARA 🔍" to "البحث عن الجولات 🔍",
            "Hızlı Operatör Filtresi:" to "فلتر سريـع:",
            "Tüm Operatörler" to "جميع منظمي الرحلات",
            "Tümünü Göster ➔" to "عرض الكل ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "باقات جولات خاصة بالوكالة.",
            "Tüm Tur Paketleri" to "جميع باقات الجولات",
            "Seçili Oteller" to "الفنادق المختارة",
            "İncele" to "استعراض",
            "Detaylar" to "التفاصيل",
            "Paket Turlar" to "باقات الجولات",
            "Gezginler Tarafından Onaylanmış Her Şey Dahil Paket Turlar" to "باقات شاملة كليًا معتمدة من المسافرين",
            "Oteller" to "الفنادق",
            "Ayrıcalıklı konaklama ve seçkin 5 yıldızlı oteller" to "إقامة حصريـة وفنادق 5 نجوم فاخرة",
            "Son Dakika" to "عروض اللحظة الأخيرة",
            "Acele edin ve %70'e varan muhteşem indirimlerden yararlanın!" to "عجل واستمتع بخصومات مذهلة تصل إلى 70%!",
            "Charter & Tarifeli Uçuşlar" to "رحلات طيران عارضة ومنتظمة",
            "En uygun fiyatlı direkt charter uçuşlar ve özel havayolu biletleri" to "أفضل رحلات الطيران المباشرة وتذاكر الطيران الخاصة",
            "Bulunan Arama Fırsatları" to "صفقات البحث المكتشفة",
            "Kriterlerinize uyan en uygun fiyatlı canlı tur ve otel teklifleri" to "أفضل عروض الجولات والفنادق المباشرة التي تطابق معاييرك",
            "İNDİRİM" to "خصم",
            "Charter Uçuş Seferi" to "رحلة عارضة",
            "Direkt Uçuş" to "رحلة مباشرة",
            "Operatör Teklifi" to "عرض المنظم",
            "Gece" to "ليالي",
            "En Düşük Fiyat" to "أدنى سعر",
            "En Yüksek Fiyat" to "أعلى سعر",
            "Tur Paketi" to "باقة الجولات",
            "Uçuşlar" to "الرحلات الجوية",
            "Destinasyon" to "الوجهة",
            "Nereye (Destinasyon / Ülke)" to "الوجهة (إلى / الدولة)",
            "Tek Yön" to "اتجاه واحد",
            "Gidiş & Dönüş" to "ذهاب وإياد",
            "Gidiş Tarihi" to "تاريخ المغادرة",
            "Dönüş Tarihi" to "تاريخ العودة",
            "Dönüş Ekleyin" to "إضافة عودة",
            "Tarih" to "التاريخ",
            "Gidiş Başlangıç" to "بداية المغادرة",
            "Gidiş Bitiş" to "نهاية المغادرة",
            "Opsiyon" to "الخيار",
            "Gece Sayısı" to "عدد الليالي",
            "Turist Sayısı" to "عدد السياح",
            "Tur Operatörü" to "منظم الرحلات",
            "Tüm Operatörler" to "جميع منظمي الرحلات",
            "Ülke" to "الدولة",
            "Türkiye" to "تركيا",
            "Tüm Ülkeler" to "جميع الدول",
            "ARAMA BAŞLAT" to "بدء البحث",
            "3 Gece" to "3 ليالي",
            "5 Gece" to "5 ليالي",
            "7 Gece" to "7 ليالي",
            "10 Gece" to "10 ليالي",
            "14 Gece" to "14 ليلة",
            "1 Yetişkin" to "بالغ واحد",
            "2 Yetişkin" to "بالغان",
            "3 Yetişkin" to "3 بالغين",
            "2 Yetişkin + 1 Çocuk" to "بالغان + طفل واحد",
            "2 Yetişkin + 2 Çocuk" to "بالغان + طفلان",
        ),
        "es" to mapOf(
            // Navigation
            "WEB YÖNETİMİ" to "GESTIÓN WEB",
            "TUR OPERATÖRLERİ" to "OPERADORES TURÍSTICOS",
            "MUHASEBE" to "CONTABILIDAD",
            "ANALİTİK" to "ANALÍTICA",
            "YEREL" to "LOCAL",
            "AYARLAR" to "AJUSTES",
            "Dashboard" to "Panel Principal",
            "Turlar" to "Tours",
            "Rezervasyon" to "Reservas",
            "Rezervasyonlar" to "Reservas",
            "Yeni Rezervasyon" to "Nueva Reserva",
            "Oteller" to "Hoteles",
            "Tur Operatörleri" to "Operadores Turísticos",
            "Ürünler" to "Productos",
            "Acente Web Sayfası" to "Sitio Web de Agencia",
            "Fiyat & Kampanya" to "Precios y Promociones",
            "Finans" to "Finanzas",
            "Fatura" to "Facturas",
            "Fatura Yönetimi" to "Gestión de Facturas",
            "Cari Hesap" to "Cuenta Corriente",
            "Cari Hesaplar" to "Cuentas Corrientes",
            "Giderler" to "Gastos",
            "Gider Girişi" to "Gastos",
            "Müşteri & CRM" to "Clientes y CRM",
            "Müşteriler & CRM" to "Clientes y CRM",
            "TO Cari Hesap" to "Cuenta Corriente TO",
            "Yerel Tur" to "Tour Local",
            "Yerel Otel" to "Hotel Local",
            "Analitik & Trend" to "Analítica y Tendencias",
            "Raporlar" to "Informes",
            "Ayarlar & Dil" to "Ajustes e Idioma",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "Ajustes de Empresa y Sitio Web",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "Gestione el logotipo, banner, título, eslogan y preferencias corporativas de la agencia",
            "Ayar Kategorileri" to "Categorías de Ajustes",
            "Genel" to "General",
            "Marka" to "Marca",
            "Banka & PayPal" to "Banco y PayPal",
            "Vergi / Sezon" to "Impuesto / Temporada",
            "Dil / Para Birimi" to "Idioma y Moneda",
            "Dil ve Para Birimi Tercihleri" to "Preferencias de Idioma y Moneda",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "Monedas e idiomas activamente soportados en el panel y sitio web de la agencia.",
            "Desteklenen Para Birimleri" to "Monedas Soportadas",
            "Desteklenen Panel Dilleri" to "Idiomas del Panel Soportados",
            "Değişiklikleri Kaydet ✓" to "Guardar Cambios ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "Catálogo de Tours",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "Gestione sus tours activos, paquetes y rutas",
            "+ Yeni Tur Ekle" to "+ Añadir Nuevo Tour",
            "Tur adı, tur kodu veya şehir ile ara..." to "Buscar por nombre, código o ciudad...",
            "Tüm Kategoriler" to "Todas las Categorías",
            "Günübirlik Tur" to "Excursión de un Día",
            "Kültür Turu" to "Tour Cultural",
            "Macera & Doğa" to "Aventura y Naturaleza",
            "Gemi & Cruise" to "Crucero y Barco",
            "VIP Özel Tur" to "Tour Privado VIP",
            "Transfer Hizmeti" to "Servicio de Traslado",
            "Tümü" to "Todos",
            "Aktif" to "Activo",
            "Pasif" to "Inactivo",
            "Düzenle" to "Editar",
            "TUR KODU & ADI" to "CÓDIGO Y NOMBRE DE TOUR",
            "KATEGORİ" to "CATEGORÍA",
            "LOKASYON & SÜRE" to "UBICACIÓN Y DURACIÓN",
            "DURUM" to "ESTADO",
            "İŞLEM" to "ACCIÓN",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "Buscador de Tours y Hoteles",
            "Kalkış Şehri (Nereden)" to "Ciudad de Salida (Desde)",
            "Nereye (Ülke / Bölge / Otel)" to "Destino (Hacia)",
            "Tur Operatörü Filtresi" to "Filtro de Operadores",
            "Maks. Bütçe (₺)" to "Presupuesto Máx. ($)",
            "TURLARI ARA 🔍" to "BUSCAR TOURS 🔍",
            "Hızlı Operatör Filtresi:" to "Filtro Rápido:",
            "Tüm Operatörler" to "Todos los Operadores",
            "Tümünü Göster ➔" to "Mostrar Todos ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "Paquetes de tours personalizados de la agencia.",
            "Tüm Tur Paketleri" to "Todos los Paquetes",
            "Seçili Oteller" to "Hoteles Seleccionados",
            "İncele" to "Revisar",
            "Detaylar" to "Detalles",
            "Paket Turlar" to "Paquetes Turísticos",
            "Gezginler Tarafından Onaylanmış Her Şey Dahil Paket Turlar" to "Paquetes Todo Incluido aprobados por viajeros",
            "Oteller" to "Hoteles",
            "Ayrıcalıklı konaklama ve seçkin 5 yıldızlı oteller" to "Alojamiento exclusivo y hoteles de 5 estrellas de élite",
            "Son Dakika" to "Última Hora",
            "Acele edin ve %70'e varan muhteşem indirimlerden yararlanın!" to "¡Date prisa y disfruta de descuentos increíbles de hasta el 70%!",
            "Charter & Tarifeli Uçuşlar" to "Vuelos Chárter y Regulares",
            "En uygun fiyatlı direkt charter uçuşlar ve özel havayolu biletleri" to "Los mejores vuelos chárter directos y billetes especiales",
            "Bulunan Arama Fırsatları" to "Ofertas de Búsqueda Encontradas",
            "Kriterlerinize uyan en uygun fiyatlı canlı tur ve otel teklifleri" to "Las mejores ofertas de tours y hoteles en vivo que coinciden con sus criterios",
            "İNDİRİM" to "DESCUENTO",
            "Charter Uçuş Seferi" to "Vuelo Chárter",
            "Direkt Uçuş" to "Vuelo Directo",
            "Operatör Teklifi" to "Oferta de Operador",
            "Gece" to "Noche(s)",
            "En Düşük Fiyat" to "Precio Mínimo",
            "En Yüksek Fiyat" to "Precio Máximo",
            "Tur Paketi" to "Paquete Turístico",
            "Uçuşlar" to "Vuelos",
            "Destinasyon" to "Destino",
            "Nereye (Destinasyon / Ülke)" to "Destino (Hacia / País)",
            "Tek Yön" to "Solo Ida",
            "Gidiş & Dönüş" to "Ida y Vuelta",
            "Gidiş Tarihi" to "Fecha de Salida",
            "Dönüş Tarihi" to "Fecha de Regreso",
            "Dönüş Ekleyin" to "Añadir Regreso",
            "Tarih" to "Fecha",
            "Gidiş Başlangıç" to "Inicio de Salida",
            "Gidiş Bitiş" to "Fin de Salida",
            "Opsiyon" to "Opción",
            "Gece Sayısı" to "Número de Noches",
            "Turist Sayısı" to "Número de Turistas",
            "Tur Operatörü" to "Operador Turístico",
            "Tüm Operatörler" to "Todos los Operadores",
            "Ülke" to "País",
            "Türkiye" to "Turquía",
            "Tüm Ülkeler" to "Todos los Países",
            "ARAMA BAŞLAT" to "INICIAR BÚSQUEDA",
            "3 Gece" to "3 Noches",
            "5 Gece" to "5 Noches",
            "7 Gece" to "7 Noches",
            "10 Gece" to "10 Noches",
            "14 Gece" to "14 Noches",
            "1 Yetişkin" to "1 Adulto",
            "2 Yetişkin" to "2 Adultos",
            "3 Yetişkin" to "3 Adultos",
            "2 Yetişkin + 1 Çocuk" to "2 Adultos + 1 Niño",
            "2 Yetişkin + 2 Çocuk" to "2 Adultos + 2 Niños",
        )
    )

    fun setLanguage(code: String) {
        val lang = supportedLanguages.find { it.code == code } ?: supportedLanguages.first()
        _currentLanguage.value = lang
    }

    fun translate(key: String): String {
        val code = _currentLanguage.value.code
        return dictionary[code]?.get(key) ?: dictionary["tr"]?.get(key) ?: key
    }
}
