package com.mgacreative.touros.ui.localization

import com.mgacreative.touros.domain.model.AppLanguageItem
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Global Canlı Dil Yöneticisi — TourOS
 *
 * Tüm platformlarda (Web, Desktop, Android, iOS) seçili uygulama dilini reaktif tutar
 * ve menü, ekran başlığı, tablo etiketleri ve buton metinlerini 6 dilde dinamik olarak çözer.
 */
object AppLanguageManager {
    val supportedLanguages = listOf(
        AppLanguageItem("tr", "Türkçe", false, "🇹🇷"),
        AppLanguageItem("en", "English", false, "🇬🇧"),
        AppLanguageItem("de", "Deutsch", false, "🇩🇪"),
        AppLanguageItem("ru", "Русский", false, "🇷🇺"),
        AppLanguageItem("ar", "العربية", true, "🇸🇦"),
        AppLanguageItem("es", "Español", false, "🇪🇸")
    )

    private val _currentLanguage = MutableStateFlow(supportedLanguages.first())
    val currentLanguage: StateFlow<AppLanguageItem> = _currentLanguage.asStateFlow()

    private val dictionary: Map<String, Map<String, String>> = mapOf(
        "tr" to mapOf(
            // Navigation
            "Dashboard" to "Dashboard",
            "Turlar" to "Turlar",
            "Rezervasyon" to "Rezervasyon",
            "Oteller" to "Oteller",
            "Tur Operatörleri" to "Tur Operatörleri",
            "Ürünler" to "Ürünler",
            "Acente Web Sayfası" to "Acente Web Sayfası",
            "Fiyat & Kampanya" to "Fiyat & Kampanya",
            "Finans" to "Finans",
            "Fatura Yönetimi" to "Fatura Yönetimi",
            "Cari Hesaplar" to "Cari Hesaplar",
            "Gider Girişi" to "Gider Girişi",
            "Müşteriler & CRM" to "Müşteriler & CRM",
            "Analitik & Trend" to "Analitik & Trend",
            "Raporlar" to "Raporlar",
            "Ayarlar & Dil" to "Ayarlar & Dil",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "Şirket & Web Sayfası Ayarları",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin",
            "Ayar Kategorileri" to "Ayar Kategorileri",
            "Genel" to "Genel",
            "Marka" to "Marka",
            "Banka & PayPal" to "Banka & PayPal",
            "Vergi / Sezon" to "Vergi / Sezon",
            "Dil / Para Birimi" to "Dil / Para Birimi",
            "Dil ve Para Birimi Tercihleri" to "Dil ve Para Birimi Tercihleri",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller.",
            "Desteklenen Para Birimleri" to "Desteklenen Para Birimleri",
            "Desteklenen Panel Dilleri" to "Desteklenen Panel Dilleri",
            "Değişiklikleri Kaydet ✓" to "Değişiklikleri Kaydet ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "Tur Kataloğu",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "Aktif turlarınızı, paketleri ve rotaları yönetin",
            "+ Yeni Tur Ekle" to "+ Yeni Tur Ekle",
            "Tur adı, tur kodu veya şehir ile ara..." to "Tur adı, tur kodu veya şehir ile ara...",
            "Tüm Kategoriler" to "Tüm Kategoriler",
            "Günübirlik Tur" to "Günübirlik Tur",
            "Kültür Turu" to "Kültür Turu",
            "Macera & Doğa" to "Macera & Doğa",
            "Gemi & Cruise" to "Gemi & Cruise",
            "VIP Özel Tur" to "VIP Özel Tur",
            "Transfer Hizmeti" to "Transfer Hizmeti",
            "Tümü" to "Tümü",
            "Aktif" to "Aktif",
            "Pasif" to "Pasif",
            "Düzenle" to "Düzenle",
            "TUR KODU & ADI" to "TUR KODU & ADI",
            "KATEGORİ" to "KATEGORİ",
            "LOKASYON & SÜRE" to "LOKASYON & SÜRE",
            "DURUM" to "DURUM",
            "İŞLEM" to "İŞLEM",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "Tur ve Otel Arama Motoru",
            "Kalkış Şehri (Nereden)" to "Kalkış Şehri (Nereden)",
            "Nereye (Ülke / Bölge / Otel)" to "Nereye (Ülke / Bölge / Otel)",
            "Tur Operatörü Filtresi" to "Tur Operatörü Filtresi",
            "Maks. Bütçe (₺)" to "Maks. Bütçe (₺)",
            "TURLARI ARA 🔍" to "TURLARI ARA 🔍",
            "Hızlı Operatör Filtresi:" to "Hızlı Operatör Filtresi:",
            "Tüm Operatörler" to "Tüm Operatörler",
            "Tümünü Göster ➔" to "Tümünü Göster ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "Acente tarafından özel oluşturulan manuel tur paketleri.",
            "Tüm Tur Paketleri" to "Tüm Tur Paketleri",
            "Seçili Oteller" to "Seçili Oteller",
            "İncele" to "İncele",
            "Detaylar" to "Detaylar"
        ),
        "en" to mapOf(
            // Navigation
            "Dashboard" to "Dashboard",
            "Turlar" to "Tours",
            "Rezervasyon" to "Bookings",
            "Oteller" to "Hotels",
            "Tur Operatörleri" to "Tour Operators",
            "Ürünler" to "Products",
            "Acente Web Sayfası" to "Agency Website",
            "Fiyat & Kampanya" to "Pricing & Campaigns",
            "Finans" to "Finance",
            "Fatura Yönetimi" to "Invoice Management",
            "Cari Hesaplar" to "Current Accounts",
            "Gider Girişi" to "Expenses",
            "Müşteriler & CRM" to "Customers & CRM",
            "Analitik & Trend" to "Analytics & Trends",
            "Raporlar" to "Reports",
            "Ayarlar & Dil" to "Settings & Language",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "Company & Website Settings",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "Manage agency website logo, header banner, title, slogan and corporate preferences",
            "Ayar Kategorileri" to "Settings Categories",
            "Genel" to "General",
            "Marka" to "Branding",
            "Banka & PayPal" to "Bank & PayPal",
            "Vergi / Sezon" to "Tax / Season",
            "Dil / Para Birimi" to "Language & Currency",
            "Dil ve Para Birimi Tercihleri" to "Language and Currency Preferences",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "Currencies and languages to be actively supported in agency panel and website.",
            "Desteklenen Para Birimleri" to "Supported Currencies",
            "Desteklenen Panel Dilleri" to "Supported Panel Languages",
            "Değişiklikleri Kaydet ✓" to "Save Changes ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "Tour Catalog",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "Manage your active tours, packages and routes",
            "+ Yeni Tur Ekle" to "+ Add New Tour",
            "Tur adı, tur kodu veya şehir ile ara..." to "Search by tour name, code or city...",
            "Tüm Kategoriler" to "All Categories",
            "Günübirlik Tur" to "Day Trip",
            "Kültür Turu" to "Cultural Tour",
            "Macera & Doğa" to "Adventure & Nature",
            "Gemi & Cruise" to "Cruise & Ship",
            "VIP Özel Tur" to "VIP Private Tour",
            "Transfer Hizmeti" to "Transfer Service",
            "Tümü" to "All",
            "Aktif" to "Active",
            "Pasif" to "Passive",
            "Düzenle" to "Edit",
            "TUR KODU & ADI" to "TOUR CODE & NAME",
            "KATEGORİ" to "CATEGORY",
            "LOKASYON & SÜRE" to "LOCATION & DURATION",
            "DURUM" to "STATUS",
            "İŞLEM" to "ACTION",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "Tour & Hotel Search Engine",
            "Kalkış Şehri (Nereden)" to "Departure City (From)",
            "Nereye (Ülke / Bölge / Otel)" to "Destination (Country / Region / Hotel)",
            "Tur Operatörü Filtresi" to "Tour Operator Filter",
            "Maks. Bütçe (₺)" to "Max Budget ($)",
            "TURLARI ARA 🔍" to "SEARCH TOURS 🔍",
            "Hızlı Operatör Filtresi:" to "Quick Operator Filter:",
            "Tüm Operatörler" to "All Operators",
            "Tümünü Göster ➔" to "Show All ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "Custom tour packages created by the agency.",
            "Tüm Tur Paketleri" to "All Tour Packages",
            "Seçili Oteller" to "Selected Hotels",
            "İncele" to "Review",
            "Detaylar" to "Details"
        ),
        "de" to mapOf(
            // Navigation
            "Dashboard" to "Dashboard",
            "Turlar" to "Touren",
            "Rezervasyon" to "Buchungen",
            "Oteller" to "Hotels",
            "Tur Operatörleri" to "Reiseveranstalter",
            "Ürünler" to "Produkte",
            "Acente Web Sayfası" to "Agentur Webseite",
            "Fiyat & Kampanya" to "Preise & Aktionen",
            "Finans" to "Finanzen",
            "Fatura Yönetimi" to "Rechnungsverwaltung",
            "Cari Hesaplar" to "Laufende Konten",
            "Gider Girişi" to "Ausgaben",
            "Müşteriler & CRM" to "Kunden & CRM",
            "Analitik & Trend" to "Analytik & Trends",
            "Raporlar" to "Berichte",
            "Ayarlar & Dil" to "Einstellungen & Sprache",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "Unternehmenseinstellungen",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "Verwalten Sie Logo, Header-Banner, Titel, Slogan und Präferenzen der Agentur",
            "Ayar Kategorileri" to "Einstellungskategorien",
            "Genel" to "Allgemein",
            "Marka" to "Marke",
            "Banka & PayPal" to "Bank & PayPal",
            "Vergi / Sezon" to "Steuer / Saison",
            "Dil / Para Birimi" to "Sprache & Währung",
            "Dil ve Para Birimi Tercihleri" to "Sprach- und Währungseinstellungen",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "Aktiv unterstützte Währungen und Sprachen im Agenturpanel und auf der Website.",
            "Desteklenen Para Birimleri" to "Unterstützte Währungen",
            "Desteklenen Panel Dilleri" to "Unterstützte Panelsprachen",
            "Değişiklikleri Kaydet ✓" to "Änderungen Speichern ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "Tourenkatalog",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "Verwalten Sie Ihre aktiven Touren, Pakete und Routen",
            "+ Yeni Tur Ekle" to "+ Neue Tour Hinzufügen",
            "Tur adı, tur kodu veya şehir ile ara..." to "Suchen Sie nach Tourname, Code oder Stadt...",
            "Tüm Kategoriler" to "Alle Kategorien",
            "Günübirlik Tur" to "Tagesausflug",
            "Kültür Turu" to "Kulturtour",
            "Macera & Doğa" to "Abenteuer & Natur",
            "Gemi & Cruise" to "Kreuzfahrt & Schiff",
            "VIP Özel Tur" to "VIP Private Tour",
            "Transfer Hizmeti" to "Transferservice",
            "Tümü" to "Alle",
            "Aktif" to "Aktiv",
            "Pasif" to "Inaktiv",
            "Düzenle" to "Bearbeiten",
            "TUR KODU & ADI" to "TOUR-CODE & NAME",
            "KATEGORİ" to "KATEGORIE",
            "LOKASYON & SÜRE" to "STANDORT & DAUER",
            "DURUM" to "STATUS",
            "İŞLEM" to "AKTION",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "Tour- & Hotelsuchmaschine",
            "Kalkış Şehri (Nereden)" to "Abfahrtsort (Von)",
            "Nereye (Ülke / Bölge / Otel)" to "Zielort (Land / Region / Hotel)",
            "Tur Operatörü Filtresi" to "Reiseveranstalter-Filter",
            "Maks. Bütçe (₺)" to "Max. Budget (€)",
            "TURLARI ARA 🔍" to "TOUREN SUCHEN 🔍",
            "Hızlı Operatör Filtresi:" to "Schnellfilter:",
            "Tüm Operatörler" to "Alle Veranstalter",
            "Tümünü Göster ➔" to "Alle Anzeigen ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "Maßgeschneiderte Tourpakete der Agentur.",
            "Tüm Tur Paketleri" to "Alle Tourpakete",
            "Seçili Oteller" to "Ausgewählte Hotels",
            "İncele" to "Überprüfen",
            "Detaylar" to "Details"
        ),
        "ru" to mapOf(
            // Navigation
            "Dashboard" to "Дашборд",
            "Turlar" to "Туры",
            "Rezervasyon" to "Бронирования",
            "Oteller" to "Отели",
            "Tur Operatörleri" to "Туроператоры",
            "Ürünler" to "Продукты",
            "Acente Web Sayfası" to "Сайт агентства",
            "Fiyat & Kampanya" to "Цены и акции",
            "Finans" to "Финансы",
            "Fatura Yönetimi" to "Управление счетами",
            "Cari Hesaplar" to "Текущие счета",
            "Gider Girişi" to "Расходы",
            "Müşteriler & CRM" to "Клиенты и CRM",
            "Analitik & Trend" to "Аналитика и тренды",
            "Raporlar" to "Отчеты",
            "Ayarlar & Dil" to "Настройки и язык",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "Настройки компании",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "Управление логотипом, банером, заголовком, слоганом и настройками сайта",
            "Ayar Kategorileri" to "Категории настроек",
            "Genel" to "Общие",
            "Marka" to "Брендинг",
            "Banka & PayPal" to "Банк и PayPal",
            "Vergi / Sezon" to "Налоги / Сезон",
            "Dil / Para Birimi" to "Язык и валюта",
            "Dil ve Para Birimi Tercihleri" to "Настройки языка и валюты",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "Валюты и языки, поддерживаемые в панели агентства и на сайте.",
            "Desteklenen Para Birimleri" to "Поддерживаемые валюты",
            "Desteklenen Panel Dilleri" to "Поддерживаемые языки панели",
            "Değişiklikleri Kaydet ✓" to "Сохранить изменения ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "Каталог туров",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "Управление турами, пакетами и маршрутами",
            "+ Yeni Tur Ekle" to "+ Добавить тур",
            "Tur adı, tur kodu veya şehir ile ara..." to "Поиск по названию, коду или городу...",
            "Tüm Kategoriler" to "Все категории",
            "Günübirlik Tur" to "Однодневный тур",
            "Kültür Turu" to "Экскурсионный тур",
            "Macera & Doğa" to "Приключения и природа",
            "Gemi & Cruise" to "Круиз",
            "VIP Özel Tur" to "VIP тур",
            "Transfer Hizmeti" to "Трансфер",
            "Tümü" to "Все",
            "Aktif" to "Активные",
            "Pasif" to "Неактивные",
            "Düzenle" to "Изменить",
            "TUR KODU & ADI" to "КОД И НАЗВАНИЕ ТУРА",
            "KATEGORİ" to "КАТЕГОРИЯ",
            "LOKASYON & SÜRE" to "ЛОКАЦИЯ И ДЛИТЕЛЬНОСТЬ",
            "DURUM" to "СТАТУС",
            "İŞLEM" to "ДЕЙСТВИЕ",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "Поиск туров и отелей",
            "Kalkış Şehri (Nereden)" to "Город вылета (Откуда)",
            "Nereye (Ülke / Bölge / Otel)" to "Направление (Куда)",
            "Tur Operatörü Filtresi" to "Фильтр туроператоров",
            "Maks. Bütçe (₺)" to "Макс. бюджет (₽)",
            "TURLARI ARA 🔍" to "ИСКАТЬ ТУРЫ 🔍",
            "Hızlı Operatör Filtresi:" to "Быстрый фильтр:",
            "Tüm Operatörler" to "Все туроператоры",
            "Tümünü Göster ➔" to "Показать все ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "Специальные туры агентства.",
            "Tüm Tur Paketleri" to "Все туры",
            "Seçили Oteller" to "Отели",
            "İncele" to "Просмотр",
            "Detaylar" to "Детали"
        ),
        "ar" to mapOf(
            // Navigation
            "Dashboard" to "لوحة التحكم",
            "Turlar" to "الجولات",
            "Rezervasyon" to "الحجوزات",
            "Oteller" to "الفنادق",
            "Tur Operatörleri" to "منظمو الرحلات",
            "Ürünler" to "المنتجات",
            "Acente Web Sayfası" to "موقع الوكالة",
            "Fiyat & Kampanya" to "الأسعار والعروض",
            "Finans" to "المالية",
            "Fatura Yönetimi" to "إدارة الفواتير",
            "Cari Hesaplar" to "الحسابات الجارية",
            "Gider Girişi" to "المصروفات",
            "Müşteriler & CRM" to "العملاء و CRM",
            "Analitik & Trend" to "التحليلات والاتجاهات",
            "Raporlar" to "التقارير",
            "Ayarlar & Dil" to "الإعدادات واللغة",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "إعدادات الشركة والموقع",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "إدارة شعار الموقع والعناوين والتفضيلات المؤسسية",
            "Ayar Kategorileri" to "فئات الإعدادات",
            "Genel" to "عام",
            "Marka" to "العلامة التجارية",
            "Banka & PayPal" to "البنك و PayPal",
            "Vergi / Sezon" to "الضرائب / الموسم",
            "Dil / Para Birimi" to "اللغة والعملة",
            "Dil ve Para Birimi Tercihleri" to "تفضيلات اللغة والعملة",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "العملات واللغات المدعومة في لوحة الوكالة والموقع الإلكتروني.",
            "Desteklenen Para Birimleri" to "العملات المدعومة",
            "Desteklenen Panel Dilleri" to "لغات اللوحة المدعومة",
            "Değişiklikleri Kaydet ✓" to "حفظ التغييرات ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "كتالوج الجولات",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "إدارة الجولات والمسارات النشطة",
            "+ Yeni Tur Ekle" to "+ إضافة جولة جديدة",
            "Tur adı, tur kodu veya şehir ile ara..." to "البحث حسب الاسم أو الرمز أو المدينة...",
            "Tüm Kategoriler" to "جميع الفئات",
            "Günübirlik Tur" to "جولة يومية",
            "Kültür Turu" to "جولة ثقافية",
            "Macera & Doğa" to "المغامرة والطبيعة",
            "Gemi & Cruise" to "رحلة بحرية",
            "VIP Özel Tur" to "جولة VIP خاصة",
            "Transfer Hizmeti" to "خدمة النقل",
            "Tümü" to "الكل",
            "Aktif" to "نشط",
            "Pasif" to "غير نشط",
            "Düzenle" to "تعديل",
            "TUR KODU & ADI" to "رمز واسم الجولة",
            "KATEGORİ" to "الفئة",
            "LOKASYON & SÜRE" to "الموقع والمدة",
            "DURUM" to "الحالة",
            "İŞLEM" to "الإجراء",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "محرك بحث الجولات والفنادق",
            "Kalkış Şehri (Nereden)" to "مدينة المغادرة (من)",
            "Nereye (Ülke / Bölge / Otel)" to "الوجهة (إلى)",
            "Tur Operatörü Filtresi" to "فلتر منظم الرحلات",
            "Maks. Bütçe (₺)" to "الحد الأقصى للميزانية ($)",
            "TURLARI ARA 🔍" to "البحث عن الجولات 🔍",
            "Hızlı Operatör Filtresi:" to "فلتر سريـع:",
            "Tüm Operatörler" to "جميع منظمي الرحلات",
            "Tümünü Göster ➔" to "عرض الكل ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "باقات جولات خاصة بالوكالة.",
            "Tüm Tur Paketleri" to "جميع باقات الجولات",
            "Seçili Oteller" to "الفنادق المختارة",
            "İncele" to "استعراض",
            "Detaylar" to "التفاصيل"
        ),
        "es" to mapOf(
            // Navigation
            "Dashboard" to "Panel Principal",
            "Turlar" to "Tours",
            "Rezervasyon" to "Reservas",
            "Oteller" to "Hoteles",
            "Tur Operatörleri" to "Operadores Turísticos",
            "Ürünler" to "Productos",
            "Acente Web Sayfası" to "Sitio Web de Agencia",
            "Fiyat & Kampanya" to "Precios y Promociones",
            "Finans" to "Finanzas",
            "Fatura Yönetimi" to "Gestión de Facturas",
            "Cari Hesaplar" to "Cuentas Corrientes",
            "Gider Girişi" to "Gastos",
            "Müşteriler & CRM" to "Clientes y CRM",
            "Analitik & Trend" to "Analítica y Tendencias",
            "Raporlar" to "Informes",
            "Ayarlar & Dil" to "Ajustes e Idioma",
            
            // Settings Screen
            "Şirket & Web Sayfası Ayarları" to "Ajustes de Empresa y Sitio Web",
            "Acente web sitesi logo, header banner, başlık, slogan ve kurumsal tercihleri yönetin" to "Gestione el logotipo, banner, título, eslogan y preferencias corporativas de la agencia",
            "Ayar Kategorileri" to "Categorías de Ajustes",
            "Genel" to "General",
            "Marka" to "Marca",
            "Banka & PayPal" to "Banco y PayPal",
            "Vergi / Sezon" to "Impuesto / Temporada",
            "Dil / Para Birimi" to "Idioma y Moneda",
            "Dil ve Para Birimi Tercihleri" to "Preferencias de Idioma y Moneda",
            "Acente panelinde ve web sitesinde aktif desteklenecek para birimleri ve diller." to "Monedas e idiomas activamente soportados en el panel y sitio web de la agencia.",
            "Desteklenen Para Birimleri" to "Monedas Soportadas",
            "Desteklenen Panel Dilleri" to "Idiomas del Panel Soportados",
            "Değişiklikleri Kaydet ✓" to "Guardar Cambios ✓",
            
            // Tour List Screen
            "Tur Kataloğu" to "Catálogo de Tours",
            "Aktif turlarınızı, paketleri ve rotaları yönetin" to "Gestione sus tours activos, paquetes y rutas",
            "+ Yeni Tur Ekle" to "+ Añadir Nuevo Tour",
            "Tur adı, tur kodu veya şehir ile ara..." to "Buscar por nombre, código o ciudad...",
            "Tüm Kategoriler" to "Todas las Categorías",
            "Günübirlik Tur" to "Excursión de un Día",
            "Kültür Turu" to "Tour Cultural",
            "Macera & Doğa" to "Aventura y Naturaleza",
            "Gemi & Cruise" to "Crucero y Barco",
            "VIP Özel Tur" to "Tour Privado VIP",
            "Transfer Hizmeti" to "Servicio de Traslado",
            "Tümü" to "Todos",
            "Aktif" to "Activo",
            "Pasif" to "Inactivo",
            "Düzenle" to "Editar",
            "TUR KODU & ADI" to "CÓDIGO Y NOMBRE DE TOUR",
            "KATEGORİ" to "CATEGORÍA",
            "LOKASYON & SÜRE" to "UBICACIÓN Y DURACIÓN",
            "DURUM" to "ESTADO",
            "İŞLEM" to "ACCIÓN",
            
            // Storefront Screen
            "Tur ve Otel Arama Motoru" to "Buscador de Tours y Hoteles",
            "Kalkış Şehri (Nereden)" to "Ciudad de Salida (Desde)",
            "Nereye (Ülke / Bölge / Otel)" to "Destino (Hacia)",
            "Tur Operatörü Filtresi" to "Filtro de Operadores",
            "Maks. Bütçe (₺)" to "Presupuesto Máx. ($)",
            "TURLARI ARA 🔍" to "BUSCAR TOURS 🔍",
            "Hızlı Operatör Filtresi:" to "Filtro Rápido:",
            "Tüm Operatörler" to "Todos los Operadores",
            "Tümünü Göster ➔" to "Mostrar Todos ➔",
            "Acente tarafından özel oluşturulan manuel tur paketleri." to "Paquetes de tours personalizados de la agencia.",
            "Tüm Tur Paketleri" to "Todos los Paquetes",
            "Seçili Oteller" to "Hoteles Seleccionados",
            "İncele" to "Revisar",
            "Detaylar" to "Detalles"
        )
    )

    fun setLanguage(code: String) {
        val lang = supportedLanguages.find { it.code == code } ?: supportedLanguages.first()
        _currentLanguage.value = lang
    }

    fun translate(key: String): String {
        val code = _currentLanguage.value.code
        return dictionary[code]?.get(key) ?: dictionary["tr"]?.get(key) ?: key
    }
}
